// GENERATED FILE - DO NOT EDIT
// Generated by tool/generate_readable_colors.dart
//
// These colors are readable on both light and dark terminal backgrounds
// and do not interfere with red (errors) or yellow (warnings).
//
// Filtering criteria:
// - Distance to red (XtermColor.red_1) > 30
// - Distance to yellow (XtermColor.yellow_3) > 30
// - Contrast on white >= 2.12
// - Contrast on black >= 3.1
// - Saturation >= 16% (excludes grays)

import 'package:chirp/src/xterm_colors.g.dart';

/// Low saturation colors (17-33%) - subtle, muted tones.
const List<XtermColor> readableColorsLowSaturation = [
  XtermColor.hotPink3_132,
  XtermColor.plum4_96,
  XtermColor.mediumOrchid3_133,
  XtermColor.grey63_139,
  XtermColor.mediumPurple3_97,
  XtermColor.mediumPurple4_60,
  XtermColor.slateBlue3_61,
  XtermColor.lightSlateGrey_103,
  XtermColor.steelBlue_67,
  XtermColor.cadetBlue_73,
  XtermColor.lightSkyBlue3_109,
  XtermColor.rosyBrown_138,
];

/// Medium saturation colors (34-60%) - balanced, clear tones.
const List<XtermColor> readableColorsMediumSaturation = [
  XtermColor.hotPink3_168,
  XtermColor.pink3_175,
  XtermColor.hotPink2_169,
  XtermColor.orchid_170,
  XtermColor.plum3_176,
  XtermColor.mediumOrchid_134,
  XtermColor.mediumPurple2_140,
  XtermColor.mediumPurple3_98,
  XtermColor.slateBlue3_62,
  XtermColor.mediumPurple_104,
  XtermColor.steelBlue3_68,
  XtermColor.lightSkyBlue3_110,
  XtermColor.skyBlue3_74,
  XtermColor.lightSalmon3_173,
  XtermColor.lightPink3_174,
];

/// High saturation colors (61-100%) - vibrant, vivid tones.
const List<XtermColor> readableColorsHighSaturation = [
  XtermColor.indianRed1_204,
  XtermColor.paleVioletRed1_211,
  XtermColor.hotPink_205,
  XtermColor.deepPink1_198,
  XtermColor.deepPink3_162,
  XtermColor.orchid2_212,
  XtermColor.deepPink1_199,
  XtermColor.hotPink_206,
  XtermColor.mediumVioletRed_126,
  XtermColor.magenta3_163,
  XtermColor.magenta2_200,
  XtermColor.magenta3_127,
  XtermColor.brightMagenta_13,
  XtermColor.mediumOrchid1_207,
  XtermColor.magenta1_201,
  XtermColor.magenta3_164,
  XtermColor.magenta2_165,
  XtermColor.darkViolet_128,
  XtermColor.mediumOrchid1_171,
  XtermColor.purple_129,
  XtermColor.violet_177,
  XtermColor.purple_93,
  XtermColor.mediumPurple2_135,
  XtermColor.mediumPurple1_141,
  XtermColor.slateBlue1_99,
  XtermColor.lightSlateBlue_105,
  XtermColor.royalBlue1_63,
  XtermColor.cornflowerBlue_69,
  XtermColor.skyBlue2_111,
  XtermColor.dodgerBlue2_27,
  XtermColor.dodgerBlue3_26,
  XtermColor.steelBlue1_75,
  XtermColor.dodgerBlue1_33,
  XtermColor.deepSkyBlue4_25,
  XtermColor.deepSkyBlue3_32,
  XtermColor.deepSkyBlue1_39,
  XtermColor.deepSkyBlue3_31,
  XtermColor.deepSkyBlue2_38,
  XtermColor.cyan_6,
  XtermColor.lightSeaGreen_37,
  XtermColor.turquoise4_30,
  XtermColor.darkOrange_208,
  XtermColor.orangeRed1_202,
  XtermColor.salmon1_209,
  XtermColor.indianRed1_203,
  XtermColor.lightCoral_210,
];

/// All readable colors combined (low + medium + high saturation).
const List<XtermColor> readableColors = [
  ...readableColorsLowSaturation,
  ...readableColorsMediumSaturation,
  ...readableColorsHighSaturation,
];
