// GENERATED FILE - DO NOT EDIT
// Generated by tool/generate_readable_colors.dart
//
// These colors are readable on both light and dark terminal backgrounds
// and do not interfere with red (errors) or yellow (warnings).
//
// Filtering criteria:
// - Distance to red (XtermColor.red) > 30
// - Distance to yellow (XtermColor.yellow) > 30
// - Contrast on white >= 2.12
// - Contrast on black >= 3.1
// - Saturation >= 16% (excludes grays)

import 'package:chirp/src/xterm_colors.g.dart';

/// Low saturation colors (17-33%) - subtle, muted tones.
const List<XtermColor> readableColorsLowSaturation = [
  XtermColor.color132,
  XtermColor.color96,
  XtermColor.color133,
  XtermColor.color139,
  XtermColor.color97,
  XtermColor.color60,
  XtermColor.color61,
  XtermColor.color103,
  XtermColor.color67,
  XtermColor.color73,
  XtermColor.color109,
  XtermColor.color138,
];

/// Medium saturation colors (34-60%) - balanced, clear tones.
const List<XtermColor> readableColorsMediumSaturation = [
  XtermColor.color168,
  XtermColor.color175,
  XtermColor.color169,
  XtermColor.color170,
  XtermColor.color176,
  XtermColor.color134,
  XtermColor.color140,
  XtermColor.color98,
  XtermColor.color62,
  XtermColor.color104,
  XtermColor.color68,
  XtermColor.color110,
  XtermColor.color74,
  XtermColor.color173,
  XtermColor.color174,
];

/// High saturation colors (61-100%) - vibrant, vivid tones.
const List<XtermColor> readableColorsHighSaturation = [
  XtermColor.color204,
  XtermColor.color211,
  XtermColor.color205,
  XtermColor.color198,
  XtermColor.color162,
  XtermColor.color212,
  XtermColor.color199,
  XtermColor.color206,
  XtermColor.color126,
  XtermColor.color163,
  XtermColor.color200,
  XtermColor.color127,
  XtermColor.brightMagenta,
  XtermColor.color207,
  XtermColor.color201,
  XtermColor.color164,
  XtermColor.color165,
  XtermColor.color128,
  XtermColor.color171,
  XtermColor.color129,
  XtermColor.color177,
  XtermColor.color93,
  XtermColor.color135,
  XtermColor.color141,
  XtermColor.color99,
  XtermColor.color105,
  XtermColor.color63,
  XtermColor.color69,
  XtermColor.color111,
  XtermColor.color27,
  XtermColor.color26,
  XtermColor.color75,
  XtermColor.color33,
  XtermColor.color25,
  XtermColor.color32,
  XtermColor.color39,
  XtermColor.color31,
  XtermColor.color38,
  XtermColor.cyan,
  XtermColor.color37,
  XtermColor.color30,
  XtermColor.color208,
  XtermColor.color202,
  XtermColor.color209,
  XtermColor.color203,
  XtermColor.color210,
];

/// All readable colors combined (low + medium + high saturation).
const List<XtermColor> readableColors = [
  ...readableColorsLowSaturation,
  ...readableColorsMediumSaturation,
  ...readableColorsHighSaturation,
];
