// GENERATED FILE - DO NOT EDIT
// Generated by tool/generate_xterm_colors.dart

import 'dart:math' as math;

/// Represents an xterm ANSI color with contrast information.
enum XtermColor {

  /// Black (#000000)
  black_0(
    code: 0,
    r: 0,
    g: 0,
    b: 0,
    luminance: 0.0000,
    contrastOnWhite: 21.00,
    contrastOnBlack: 1.00,
  ),

  /// Maroon (#800000)
  red_1(
    code: 1,
    r: 128,
    g: 0,
    b: 0,
    luminance: 0.0459,
    contrastOnWhite: 10.95,
    contrastOnBlack: 1.92,
  ),

  /// Green (#008000)
  green_2(
    code: 2,
    r: 0,
    g: 128,
    b: 0,
    luminance: 0.1544,
    contrastOnWhite: 5.14,
    contrastOnBlack: 4.09,
  ),

  /// Olive (#808000)
  yellow_3(
    code: 3,
    r: 128,
    g: 128,
    b: 0,
    luminance: 0.2003,
    contrastOnWhite: 4.20,
    contrastOnBlack: 5.01,
  ),

  /// Navy (#000080)
  blue_4(
    code: 4,
    r: 0,
    g: 0,
    b: 128,
    luminance: 0.0156,
    contrastOnWhite: 16.01,
    contrastOnBlack: 1.31,
  ),

  /// Purple (#800080)
  magenta_5(
    code: 5,
    r: 128,
    g: 0,
    b: 128,
    luminance: 0.0615,
    contrastOnWhite: 9.42,
    contrastOnBlack: 2.23,
  ),

  /// Teal (#008080)
  cyan_6(
    code: 6,
    r: 0,
    g: 128,
    b: 128,
    luminance: 0.1700,
    contrastOnWhite: 4.77,
    contrastOnBlack: 4.40,
  ),

  /// Silver (#c0c0c0)
  white_7(
    code: 7,
    r: 192,
    g: 192,
    b: 192,
    luminance: 0.5271,
    contrastOnWhite: 1.82,
    contrastOnBlack: 11.54,
  ),

  /// Grey (#808080)
  brightBlack_8(
    code: 8,
    r: 128,
    g: 128,
    b: 128,
    luminance: 0.2159,
    contrastOnWhite: 3.95,
    contrastOnBlack: 5.32,
  ),

  /// Red (#ff0000)
  brightRed_9(
    code: 9,
    r: 255,
    g: 0,
    b: 0,
    luminance: 0.2126,
    contrastOnWhite: 4.00,
    contrastOnBlack: 5.25,
  ),

  /// Lime (#00ff00)
  brightGreen_10(
    code: 10,
    r: 0,
    g: 255,
    b: 0,
    luminance: 0.7152,
    contrastOnWhite: 1.37,
    contrastOnBlack: 15.30,
  ),

  /// Yellow (#ffff00)
  brightYellow_11(
    code: 11,
    r: 255,
    g: 255,
    b: 0,
    luminance: 0.9278,
    contrastOnWhite: 1.07,
    contrastOnBlack: 19.56,
  ),

  /// Blue (#0000ff)
  brightBlue_12(
    code: 12,
    r: 0,
    g: 0,
    b: 255,
    luminance: 0.0722,
    contrastOnWhite: 8.59,
    contrastOnBlack: 2.44,
  ),

  /// Fuchsia (#ff00ff)
  brightMagenta_13(
    code: 13,
    r: 255,
    g: 0,
    b: 255,
    luminance: 0.2848,
    contrastOnWhite: 3.14,
    contrastOnBlack: 6.70,
  ),

  /// Aqua (#00ffff)
  brightCyan_14(
    code: 14,
    r: 0,
    g: 255,
    b: 255,
    luminance: 0.7874,
    contrastOnWhite: 1.25,
    contrastOnBlack: 16.75,
  ),

  /// White (#ffffff)
  brightWhite_15(
    code: 15,
    r: 255,
    g: 255,
    b: 255,
    luminance: 1.0000,
    contrastOnWhite: 1.00,
    contrastOnBlack: 21.00,
  ),

  /// Grey0 (#000000)
  grey0_16(
    code: 16,
    r: 0,
    g: 0,
    b: 0,
    luminance: 0.0000,
    contrastOnWhite: 21.00,
    contrastOnBlack: 1.00,
  ),

  /// NavyBlue (#00005f)
  navyBlue_17(
    code: 17,
    r: 0,
    g: 0,
    b: 95,
    luminance: 0.0083,
    contrastOnWhite: 18.02,
    contrastOnBlack: 1.17,
  ),

  /// DarkBlue (#000087)
  darkBlue_18(
    code: 18,
    r: 0,
    g: 0,
    b: 135,
    luminance: 0.0175,
    contrastOnWhite: 15.56,
    contrastOnBlack: 1.35,
  ),

  /// Blue3 (#0000af)
  blue3_19(
    code: 19,
    r: 0,
    g: 0,
    b: 175,
    luminance: 0.0310,
    contrastOnWhite: 12.97,
    contrastOnBlack: 1.62,
  ),

  /// Blue3 (#0000d7)
  blue3_20(
    code: 20,
    r: 0,
    g: 0,
    b: 215,
    luminance: 0.0491,
    contrastOnWhite: 10.60,
    contrastOnBlack: 1.98,
  ),

  /// Blue1 (#0000ff)
  blue1_21(
    code: 21,
    r: 0,
    g: 0,
    b: 255,
    luminance: 0.0722,
    contrastOnWhite: 8.59,
    contrastOnBlack: 2.44,
  ),

  /// DarkGreen (#005f00)
  darkGreen_22(
    code: 22,
    r: 0,
    g: 95,
    b: 0,
    luminance: 0.0818,
    contrastOnWhite: 7.96,
    contrastOnBlack: 2.64,
  ),

  /// DeepSkyBlue4 (#005f5f)
  deepSkyBlue4_23(
    code: 23,
    r: 0,
    g: 95,
    b: 95,
    luminance: 0.0901,
    contrastOnWhite: 7.49,
    contrastOnBlack: 2.80,
  ),

  /// DeepSkyBlue4 (#005f87)
  deepSkyBlue4_24(
    code: 24,
    r: 0,
    g: 95,
    b: 135,
    luminance: 0.0993,
    contrastOnWhite: 7.03,
    contrastOnBlack: 2.99,
  ),

  /// DeepSkyBlue4 (#005faf)
  deepSkyBlue4_25(
    code: 25,
    r: 0,
    g: 95,
    b: 175,
    luminance: 0.1128,
    contrastOnWhite: 6.45,
    contrastOnBlack: 3.26,
  ),

  /// DodgerBlue3 (#005fd7)
  dodgerBlue3_26(
    code: 26,
    r: 0,
    g: 95,
    b: 215,
    luminance: 0.1309,
    contrastOnWhite: 5.80,
    contrastOnBlack: 3.62,
  ),

  /// DodgerBlue2 (#005fff)
  dodgerBlue2_27(
    code: 27,
    r: 0,
    g: 95,
    b: 255,
    luminance: 0.1540,
    contrastOnWhite: 5.15,
    contrastOnBlack: 4.08,
  ),

  /// Green4 (#008700)
  green4_28(
    code: 28,
    r: 0,
    g: 135,
    b: 0,
    luminance: 0.1733,
    contrastOnWhite: 4.70,
    contrastOnBlack: 4.47,
  ),

  /// SpringGreen4 (#00875f)
  springGreen4_29(
    code: 29,
    r: 0,
    g: 135,
    b: 95,
    luminance: 0.1815,
    contrastOnWhite: 4.53,
    contrastOnBlack: 4.63,
  ),

  /// Turquoise4 (#008787)
  turquoise4_30(
    code: 30,
    r: 0,
    g: 135,
    b: 135,
    luminance: 0.1908,
    contrastOnWhite: 4.36,
    contrastOnBlack: 4.82,
  ),

  /// DeepSkyBlue3 (#0087af)
  deepSkyBlue3_31(
    code: 31,
    r: 0,
    g: 135,
    b: 175,
    luminance: 0.2042,
    contrastOnWhite: 4.13,
    contrastOnBlack: 5.08,
  ),

  /// DeepSkyBlue3 (#0087d7)
  deepSkyBlue3_32(
    code: 32,
    r: 0,
    g: 135,
    b: 215,
    luminance: 0.2223,
    contrastOnWhite: 3.86,
    contrastOnBlack: 5.45,
  ),

  /// DodgerBlue1 (#0087ff)
  dodgerBlue1_33(
    code: 33,
    r: 0,
    g: 135,
    b: 255,
    luminance: 0.2455,
    contrastOnWhite: 3.55,
    contrastOnBlack: 5.91,
  ),

  /// Green3 (#00af00)
  green3_34(
    code: 34,
    r: 0,
    g: 175,
    b: 0,
    luminance: 0.3066,
    contrastOnWhite: 2.94,
    contrastOnBlack: 7.13,
  ),

  /// SpringGreen3 (#00af5f)
  springGreen3_35(
    code: 35,
    r: 0,
    g: 175,
    b: 95,
    luminance: 0.3149,
    contrastOnWhite: 2.88,
    contrastOnBlack: 7.30,
  ),

  /// DarkCyan (#00af87)
  darkCyan_36(
    code: 36,
    r: 0,
    g: 175,
    b: 135,
    luminance: 0.3241,
    contrastOnWhite: 2.81,
    contrastOnBlack: 7.48,
  ),

  /// LightSeaGreen (#00afaf)
  lightSeaGreen_37(
    code: 37,
    r: 0,
    g: 175,
    b: 175,
    luminance: 0.3376,
    contrastOnWhite: 2.71,
    contrastOnBlack: 7.75,
  ),

  /// DeepSkyBlue2 (#00afd7)
  deepSkyBlue2_38(
    code: 38,
    r: 0,
    g: 175,
    b: 215,
    luminance: 0.3557,
    contrastOnWhite: 2.59,
    contrastOnBlack: 8.11,
  ),

  /// DeepSkyBlue1 (#00afff)
  deepSkyBlue1_39(
    code: 39,
    r: 0,
    g: 175,
    b: 255,
    luminance: 0.3788,
    contrastOnWhite: 2.45,
    contrastOnBlack: 8.58,
  ),

  /// Green3 (#00d700)
  green3_40(
    code: 40,
    r: 0,
    g: 215,
    b: 0,
    luminance: 0.4860,
    contrastOnWhite: 1.96,
    contrastOnBlack: 10.72,
  ),

  /// SpringGreen3 (#00d75f)
  springGreen3_41(
    code: 41,
    r: 0,
    g: 215,
    b: 95,
    luminance: 0.4943,
    contrastOnWhite: 1.93,
    contrastOnBlack: 10.89,
  ),

  /// SpringGreen2 (#00d787)
  springGreen2_42(
    code: 42,
    r: 0,
    g: 215,
    b: 135,
    luminance: 0.5035,
    contrastOnWhite: 1.90,
    contrastOnBlack: 11.07,
  ),

  /// Cyan3 (#00d7af)
  cyan3_43(
    code: 43,
    r: 0,
    g: 215,
    b: 175,
    luminance: 0.5170,
    contrastOnWhite: 1.85,
    contrastOnBlack: 11.34,
  ),

  /// DarkTurquoise (#00d7d7)
  darkTurquoise_44(
    code: 44,
    r: 0,
    g: 215,
    b: 215,
    luminance: 0.5351,
    contrastOnWhite: 1.79,
    contrastOnBlack: 11.70,
  ),

  /// Turquoise2 (#00d7ff)
  turquoise2_45(
    code: 45,
    r: 0,
    g: 215,
    b: 255,
    luminance: 0.5582,
    contrastOnWhite: 1.73,
    contrastOnBlack: 12.16,
  ),

  /// Green1 (#00ff00)
  green1_46(
    code: 46,
    r: 0,
    g: 255,
    b: 0,
    luminance: 0.7152,
    contrastOnWhite: 1.37,
    contrastOnBlack: 15.30,
  ),

  /// SpringGreen2 (#00ff5f)
  springGreen2_47(
    code: 47,
    r: 0,
    g: 255,
    b: 95,
    luminance: 0.7235,
    contrastOnWhite: 1.36,
    contrastOnBlack: 15.47,
  ),

  /// SpringGreen1 (#00ff87)
  springGreen1_48(
    code: 48,
    r: 0,
    g: 255,
    b: 135,
    luminance: 0.7327,
    contrastOnWhite: 1.34,
    contrastOnBlack: 15.65,
  ),

  /// MediumSpringGreen (#00ffaf)
  mediumSpringGreen_49(
    code: 49,
    r: 0,
    g: 255,
    b: 175,
    luminance: 0.7462,
    contrastOnWhite: 1.32,
    contrastOnBlack: 15.92,
  ),

  /// Cyan2 (#00ffd7)
  cyan2_50(
    code: 50,
    r: 0,
    g: 255,
    b: 215,
    luminance: 0.7643,
    contrastOnWhite: 1.29,
    contrastOnBlack: 16.29,
  ),

  /// Cyan1 (#00ffff)
  cyan1_51(
    code: 51,
    r: 0,
    g: 255,
    b: 255,
    luminance: 0.7874,
    contrastOnWhite: 1.25,
    contrastOnBlack: 16.75,
  ),

  /// DarkRed (#5f0000)
  darkRed_52(
    code: 52,
    r: 95,
    g: 0,
    b: 0,
    luminance: 0.0243,
    contrastOnWhite: 14.13,
    contrastOnBlack: 1.49,
  ),

  /// DeepPink4 (#5f005f)
  deepPink4_53(
    code: 53,
    r: 95,
    g: 0,
    b: 95,
    luminance: 0.0326,
    contrastOnWhite: 12.71,
    contrastOnBlack: 1.65,
  ),

  /// Purple4 (#5f0087)
  purple4_54(
    code: 54,
    r: 95,
    g: 0,
    b: 135,
    luminance: 0.0418,
    contrastOnWhite: 11.44,
    contrastOnBlack: 1.84,
  ),

  /// Purple4 (#5f00af)
  purple4_55(
    code: 55,
    r: 95,
    g: 0,
    b: 175,
    luminance: 0.0553,
    contrastOnWhite: 9.97,
    contrastOnBlack: 2.11,
  ),

  /// Purple3 (#5f00d7)
  purple3_56(
    code: 56,
    r: 95,
    g: 0,
    b: 215,
    luminance: 0.0734,
    contrastOnWhite: 8.51,
    contrastOnBlack: 2.47,
  ),

  /// BlueViolet (#5f00ff)
  blueViolet_57(
    code: 57,
    r: 95,
    g: 0,
    b: 255,
    luminance: 0.0965,
    contrastOnWhite: 7.17,
    contrastOnBlack: 2.93,
  ),

  /// Orange4 (#5f5f00)
  orange4_58(
    code: 58,
    r: 95,
    g: 95,
    b: 0,
    luminance: 0.1062,
    contrastOnWhite: 6.72,
    contrastOnBlack: 3.12,
  ),

  /// Grey37 (#5f5f5f)
  grey37_59(
    code: 59,
    r: 95,
    g: 95,
    b: 95,
    luminance: 0.1144,
    contrastOnWhite: 6.39,
    contrastOnBlack: 3.29,
  ),

  /// MediumPurple4 (#5f5f87)
  mediumPurple4_60(
    code: 60,
    r: 95,
    g: 95,
    b: 135,
    luminance: 0.1237,
    contrastOnWhite: 6.05,
    contrastOnBlack: 3.47,
  ),

  /// SlateBlue3 (#5f5faf)
  slateBlue3_61(
    code: 61,
    r: 95,
    g: 95,
    b: 175,
    luminance: 0.1371,
    contrastOnWhite: 5.61,
    contrastOnBlack: 3.74,
  ),

  /// SlateBlue3 (#5f5fd7)
  slateBlue3_62(
    code: 62,
    r: 95,
    g: 95,
    b: 215,
    luminance: 0.1552,
    contrastOnWhite: 5.12,
    contrastOnBlack: 4.10,
  ),

  /// RoyalBlue1 (#5f5fff)
  royalBlue1_63(
    code: 63,
    r: 95,
    g: 95,
    b: 255,
    luminance: 0.1784,
    contrastOnWhite: 4.60,
    contrastOnBlack: 4.57,
  ),

  /// Chartreuse4 (#5f8700)
  chartreuse4_64(
    code: 64,
    r: 95,
    g: 135,
    b: 0,
    luminance: 0.1976,
    contrastOnWhite: 4.24,
    contrastOnBlack: 4.95,
  ),

  /// DarkSeaGreen4 (#5f875f)
  darkSeaGreen4_65(
    code: 65,
    r: 95,
    g: 135,
    b: 95,
    luminance: 0.2059,
    contrastOnWhite: 4.10,
    contrastOnBlack: 5.12,
  ),

  /// PaleTurquoise4 (#5f8787)
  paleTurquoise4_66(
    code: 66,
    r: 95,
    g: 135,
    b: 135,
    luminance: 0.2151,
    contrastOnWhite: 3.96,
    contrastOnBlack: 5.30,
  ),

  /// SteelBlue (#5f87af)
  steelBlue_67(
    code: 67,
    r: 95,
    g: 135,
    b: 175,
    luminance: 0.2286,
    contrastOnWhite: 3.77,
    contrastOnBlack: 5.57,
  ),

  /// SteelBlue3 (#5f87d7)
  steelBlue3_68(
    code: 68,
    r: 95,
    g: 135,
    b: 215,
    luminance: 0.2467,
    contrastOnWhite: 3.54,
    contrastOnBlack: 5.93,
  ),

  /// CornflowerBlue (#5f87ff)
  cornflowerBlue_69(
    code: 69,
    r: 95,
    g: 135,
    b: 255,
    luminance: 0.2698,
    contrastOnWhite: 3.28,
    contrastOnBlack: 6.40,
  ),

  /// Chartreuse3 (#5faf00)
  chartreuse3_70(
    code: 70,
    r: 95,
    g: 175,
    b: 0,
    luminance: 0.3309,
    contrastOnWhite: 2.76,
    contrastOnBlack: 7.62,
  ),

  /// DarkSeaGreen4 (#5faf5f)
  darkSeaGreen4_71(
    code: 71,
    r: 95,
    g: 175,
    b: 95,
    luminance: 0.3392,
    contrastOnWhite: 2.70,
    contrastOnBlack: 7.78,
  ),

  /// CadetBlue (#5faf87)
  cadetBlue_72(
    code: 72,
    r: 95,
    g: 175,
    b: 135,
    luminance: 0.3484,
    contrastOnWhite: 2.64,
    contrastOnBlack: 7.97,
  ),

  /// CadetBlue (#5fafaf)
  cadetBlue_73(
    code: 73,
    r: 95,
    g: 175,
    b: 175,
    luminance: 0.3619,
    contrastOnWhite: 2.55,
    contrastOnBlack: 8.24,
  ),

  /// SkyBlue3 (#5fafd7)
  skyBlue3_74(
    code: 74,
    r: 95,
    g: 175,
    b: 215,
    luminance: 0.3800,
    contrastOnWhite: 2.44,
    contrastOnBlack: 8.60,
  ),

  /// SteelBlue1 (#5fafff)
  steelBlue1_75(
    code: 75,
    r: 95,
    g: 175,
    b: 255,
    luminance: 0.4031,
    contrastOnWhite: 2.32,
    contrastOnBlack: 9.06,
  ),

  /// Chartreuse3 (#5fd700)
  chartreuse3_76(
    code: 76,
    r: 95,
    g: 215,
    b: 0,
    luminance: 0.5103,
    contrastOnWhite: 1.87,
    contrastOnBlack: 11.21,
  ),

  /// PaleGreen3 (#5fd75f)
  paleGreen3_77(
    code: 77,
    r: 95,
    g: 215,
    b: 95,
    luminance: 0.5186,
    contrastOnWhite: 1.85,
    contrastOnBlack: 11.37,
  ),

  /// SeaGreen3 (#5fd787)
  seaGreen3_78(
    code: 78,
    r: 95,
    g: 215,
    b: 135,
    luminance: 0.5278,
    contrastOnWhite: 1.82,
    contrastOnBlack: 11.56,
  ),

  /// Aquamarine3 (#5fd7af)
  aquamarine3_79(
    code: 79,
    r: 95,
    g: 215,
    b: 175,
    luminance: 0.5413,
    contrastOnWhite: 1.78,
    contrastOnBlack: 11.83,
  ),

  /// MediumTurquoise (#5fd7d7)
  mediumTurquoise_80(
    code: 80,
    r: 95,
    g: 215,
    b: 215,
    luminance: 0.5594,
    contrastOnWhite: 1.72,
    contrastOnBlack: 12.19,
  ),

  /// SteelBlue1 (#5fd7ff)
  steelBlue1_81(
    code: 81,
    r: 95,
    g: 215,
    b: 255,
    luminance: 0.5825,
    contrastOnWhite: 1.66,
    contrastOnBlack: 12.65,
  ),

  /// Chartreuse2 (#5fff00)
  chartreuse2_82(
    code: 82,
    r: 95,
    g: 255,
    b: 0,
    luminance: 0.7395,
    contrastOnWhite: 1.33,
    contrastOnBlack: 15.79,
  ),

  /// SeaGreen2 (#5fff5f)
  seaGreen2_83(
    code: 83,
    r: 95,
    g: 255,
    b: 95,
    luminance: 0.7478,
    contrastOnWhite: 1.32,
    contrastOnBlack: 15.96,
  ),

  /// SeaGreen1 (#5fff87)
  seaGreen1_84(
    code: 84,
    r: 95,
    g: 255,
    b: 135,
    luminance: 0.7570,
    contrastOnWhite: 1.30,
    contrastOnBlack: 16.14,
  ),

  /// SeaGreen1 (#5fffaf)
  seaGreen1_85(
    code: 85,
    r: 95,
    g: 255,
    b: 175,
    luminance: 0.7705,
    contrastOnWhite: 1.28,
    contrastOnBlack: 16.41,
  ),

  /// Aquamarine1 (#5fffd7)
  aquamarine1_86(
    code: 86,
    r: 95,
    g: 255,
    b: 215,
    luminance: 0.7886,
    contrastOnWhite: 1.25,
    contrastOnBlack: 16.77,
  ),

  /// DarkSlateGray2 (#5fffff)
  darkSlateGray2_87(
    code: 87,
    r: 95,
    g: 255,
    b: 255,
    luminance: 0.8117,
    contrastOnWhite: 1.22,
    contrastOnBlack: 17.23,
  ),

  /// DarkRed (#870000)
  darkRed_88(
    code: 88,
    r: 135,
    g: 0,
    b: 0,
    luminance: 0.0515,
    contrastOnWhite: 10.34,
    contrastOnBlack: 2.03,
  ),

  /// DeepPink4 (#87005f)
  deepPink4_89(
    code: 89,
    r: 135,
    g: 0,
    b: 95,
    luminance: 0.0598,
    contrastOnWhite: 9.57,
    contrastOnBlack: 2.20,
  ),

  /// DarkMagenta (#870087)
  darkMagenta_90(
    code: 90,
    r: 135,
    g: 0,
    b: 135,
    luminance: 0.0690,
    contrastOnWhite: 8.82,
    contrastOnBlack: 2.38,
  ),

  /// DarkMagenta (#8700af)
  darkMagenta_91(
    code: 91,
    r: 135,
    g: 0,
    b: 175,
    luminance: 0.0825,
    contrastOnWhite: 7.93,
    contrastOnBlack: 2.65,
  ),

  /// DarkViolet (#8700d7)
  darkViolet_92(
    code: 92,
    r: 135,
    g: 0,
    b: 215,
    luminance: 0.1006,
    contrastOnWhite: 6.97,
    contrastOnBlack: 3.01,
  ),

  /// Purple (#8700ff)
  purple_93(
    code: 93,
    r: 135,
    g: 0,
    b: 255,
    luminance: 0.1237,
    contrastOnWhite: 6.04,
    contrastOnBlack: 3.47,
  ),

  /// Orange4 (#875f00)
  orange4_94(
    code: 94,
    r: 135,
    g: 95,
    b: 0,
    luminance: 0.1334,
    contrastOnWhite: 5.73,
    contrastOnBlack: 3.67,
  ),

  /// LightPink4 (#875f5f)
  lightPink4_95(
    code: 95,
    r: 135,
    g: 95,
    b: 95,
    luminance: 0.1416,
    contrastOnWhite: 5.48,
    contrastOnBlack: 3.83,
  ),

  /// Plum4 (#875f87)
  plum4_96(
    code: 96,
    r: 135,
    g: 95,
    b: 135,
    luminance: 0.1508,
    contrastOnWhite: 5.23,
    contrastOnBlack: 4.02,
  ),

  /// MediumPurple3 (#875faf)
  mediumPurple3_97(
    code: 97,
    r: 135,
    g: 95,
    b: 175,
    luminance: 0.1643,
    contrastOnWhite: 4.90,
    contrastOnBlack: 4.29,
  ),

  /// MediumPurple3 (#875fd7)
  mediumPurple3_98(
    code: 98,
    r: 135,
    g: 95,
    b: 215,
    luminance: 0.1824,
    contrastOnWhite: 4.52,
    contrastOnBlack: 4.65,
  ),

  /// SlateBlue1 (#875fff)
  slateBlue1_99(
    code: 99,
    r: 135,
    g: 95,
    b: 255,
    luminance: 0.2056,
    contrastOnWhite: 4.11,
    contrastOnBlack: 5.11,
  ),

  /// Yellow4 (#878700)
  yellow4_100(
    code: 100,
    r: 135,
    g: 135,
    b: 0,
    luminance: 0.2248,
    contrastOnWhite: 3.82,
    contrastOnBlack: 5.50,
  ),

  /// Wheat4 (#87875f)
  wheat4_101(
    code: 101,
    r: 135,
    g: 135,
    b: 95,
    luminance: 0.2331,
    contrastOnWhite: 3.71,
    contrastOnBlack: 5.66,
  ),

  /// Grey53 (#878787)
  grey53_102(
    code: 102,
    r: 135,
    g: 135,
    b: 135,
    luminance: 0.2423,
    contrastOnWhite: 3.59,
    contrastOnBlack: 5.85,
  ),

  /// LightSlateGrey (#8787af)
  lightSlateGrey_103(
    code: 103,
    r: 135,
    g: 135,
    b: 175,
    luminance: 0.2557,
    contrastOnWhite: 3.43,
    contrastOnBlack: 6.11,
  ),

  /// MediumPurple (#8787d7)
  mediumPurple_104(
    code: 104,
    r: 135,
    g: 135,
    b: 215,
    luminance: 0.2739,
    contrastOnWhite: 3.24,
    contrastOnBlack: 6.48,
  ),

  /// LightSlateBlue (#8787ff)
  lightSlateBlue_105(
    code: 105,
    r: 135,
    g: 135,
    b: 255,
    luminance: 0.2970,
    contrastOnWhite: 3.03,
    contrastOnBlack: 6.94,
  ),

  /// Yellow4 (#87af00)
  yellow4_106(
    code: 106,
    r: 135,
    g: 175,
    b: 0,
    luminance: 0.3581,
    contrastOnWhite: 2.57,
    contrastOnBlack: 8.16,
  ),

  /// DarkOliveGreen3 (#87af5f)
  darkOliveGreen3_107(
    code: 107,
    r: 135,
    g: 175,
    b: 95,
    luminance: 0.3664,
    contrastOnWhite: 2.52,
    contrastOnBlack: 8.33,
  ),

  /// DarkSeaGreen (#87af87)
  darkSeaGreen_108(
    code: 108,
    r: 135,
    g: 175,
    b: 135,
    luminance: 0.3756,
    contrastOnWhite: 2.47,
    contrastOnBlack: 8.51,
  ),

  /// LightSkyBlue3 (#87afaf)
  lightSkyBlue3_109(
    code: 109,
    r: 135,
    g: 175,
    b: 175,
    luminance: 0.3891,
    contrastOnWhite: 2.39,
    contrastOnBlack: 8.78,
  ),

  /// LightSkyBlue3 (#87afd7)
  lightSkyBlue3_110(
    code: 110,
    r: 135,
    g: 175,
    b: 215,
    luminance: 0.4072,
    contrastOnWhite: 2.30,
    contrastOnBlack: 9.14,
  ),

  /// SkyBlue2 (#87afff)
  skyBlue2_111(
    code: 111,
    r: 135,
    g: 175,
    b: 255,
    luminance: 0.4303,
    contrastOnWhite: 2.19,
    contrastOnBlack: 9.61,
  ),

  /// Chartreuse2 (#87d700)
  chartreuse2_112(
    code: 112,
    r: 135,
    g: 215,
    b: 0,
    luminance: 0.5375,
    contrastOnWhite: 1.79,
    contrastOnBlack: 11.75,
  ),

  /// DarkOliveGreen3 (#87d75f)
  darkOliveGreen3_113(
    code: 113,
    r: 135,
    g: 215,
    b: 95,
    luminance: 0.5458,
    contrastOnWhite: 1.76,
    contrastOnBlack: 11.92,
  ),

  /// PaleGreen3 (#87d787)
  paleGreen3_114(
    code: 114,
    r: 135,
    g: 215,
    b: 135,
    luminance: 0.5550,
    contrastOnWhite: 1.74,
    contrastOnBlack: 12.10,
  ),

  /// DarkSeaGreen3 (#87d7af)
  darkSeaGreen3_115(
    code: 115,
    r: 135,
    g: 215,
    b: 175,
    luminance: 0.5685,
    contrastOnWhite: 1.70,
    contrastOnBlack: 12.37,
  ),

  /// DarkSlateGray3 (#87d7d7)
  darkSlateGray3_116(
    code: 116,
    r: 135,
    g: 215,
    b: 215,
    luminance: 0.5866,
    contrastOnWhite: 1.65,
    contrastOnBlack: 12.73,
  ),

  /// SkyBlue1 (#87d7ff)
  skyBlue1_117(
    code: 117,
    r: 135,
    g: 215,
    b: 255,
    luminance: 0.6097,
    contrastOnWhite: 1.59,
    contrastOnBlack: 13.19,
  ),

  /// Chartreuse1 (#87ff00)
  chartreuse1_118(
    code: 118,
    r: 135,
    g: 255,
    b: 0,
    luminance: 0.7667,
    contrastOnWhite: 1.29,
    contrastOnBlack: 16.33,
  ),

  /// LightGreen (#87ff5f)
  lightGreen_119(
    code: 119,
    r: 135,
    g: 255,
    b: 95,
    luminance: 0.7750,
    contrastOnWhite: 1.27,
    contrastOnBlack: 16.50,
  ),

  /// LightGreen (#87ff87)
  lightGreen_120(
    code: 120,
    r: 135,
    g: 255,
    b: 135,
    luminance: 0.7842,
    contrastOnWhite: 1.26,
    contrastOnBlack: 16.68,
  ),

  /// PaleGreen1 (#87ffaf)
  paleGreen1_121(
    code: 121,
    r: 135,
    g: 255,
    b: 175,
    luminance: 0.7977,
    contrastOnWhite: 1.24,
    contrastOnBlack: 16.95,
  ),

  /// Aquamarine1 (#87ffd7)
  aquamarine1_122(
    code: 122,
    r: 135,
    g: 255,
    b: 215,
    luminance: 0.8158,
    contrastOnWhite: 1.21,
    contrastOnBlack: 17.32,
  ),

  /// DarkSlateGray1 (#87ffff)
  darkSlateGray1_123(
    code: 123,
    r: 135,
    g: 255,
    b: 255,
    luminance: 0.8389,
    contrastOnWhite: 1.18,
    contrastOnBlack: 17.78,
  ),

  /// Red3 (#af0000)
  red3_124(
    code: 124,
    r: 175,
    g: 0,
    b: 0,
    luminance: 0.0911,
    contrastOnWhite: 7.44,
    contrastOnBlack: 2.82,
  ),

  /// DeepPink4 (#af005f)
  deepPink4_125(
    code: 125,
    r: 175,
    g: 0,
    b: 95,
    luminance: 0.0994,
    contrastOnWhite: 7.03,
    contrastOnBlack: 2.99,
  ),

  /// MediumVioletRed (#af0087)
  mediumVioletRed_126(
    code: 126,
    r: 175,
    g: 0,
    b: 135,
    luminance: 0.1086,
    contrastOnWhite: 6.62,
    contrastOnBlack: 3.17,
  ),

  /// Magenta3 (#af00af)
  magenta3_127(
    code: 127,
    r: 175,
    g: 0,
    b: 175,
    luminance: 0.1221,
    contrastOnWhite: 6.10,
    contrastOnBlack: 3.44,
  ),

  /// DarkViolet (#af00d7)
  darkViolet_128(
    code: 128,
    r: 175,
    g: 0,
    b: 215,
    luminance: 0.1402,
    contrastOnWhite: 5.52,
    contrastOnBlack: 3.80,
  ),

  /// Purple (#af00ff)
  purple_129(
    code: 129,
    r: 175,
    g: 0,
    b: 255,
    luminance: 0.1633,
    contrastOnWhite: 4.92,
    contrastOnBlack: 4.27,
  ),

  /// DarkOrange3 (#af5f00)
  darkOrange3_130(
    code: 130,
    r: 175,
    g: 95,
    b: 0,
    luminance: 0.1730,
    contrastOnWhite: 4.71,
    contrastOnBlack: 4.46,
  ),

  /// IndianRed (#af5f5f)
  indianRed_131(
    code: 131,
    r: 175,
    g: 95,
    b: 95,
    luminance: 0.1812,
    contrastOnWhite: 4.54,
    contrastOnBlack: 4.62,
  ),

  /// HotPink3 (#af5f87)
  hotPink3_132(
    code: 132,
    r: 175,
    g: 95,
    b: 135,
    luminance: 0.1905,
    contrastOnWhite: 4.37,
    contrastOnBlack: 4.81,
  ),

  /// MediumOrchid3 (#af5faf)
  mediumOrchid3_133(
    code: 133,
    r: 175,
    g: 95,
    b: 175,
    luminance: 0.2039,
    contrastOnWhite: 4.13,
    contrastOnBlack: 5.08,
  ),

  /// MediumOrchid (#af5fd7)
  mediumOrchid_134(
    code: 134,
    r: 175,
    g: 95,
    b: 215,
    luminance: 0.2220,
    contrastOnWhite: 3.86,
    contrastOnBlack: 5.44,
  ),

  /// MediumPurple2 (#af5fff)
  mediumPurple2_135(
    code: 135,
    r: 175,
    g: 95,
    b: 255,
    luminance: 0.2452,
    contrastOnWhite: 3.56,
    contrastOnBlack: 5.90,
  ),

  /// DarkGoldenrod (#af8700)
  darkGoldenrod_136(
    code: 136,
    r: 175,
    g: 135,
    b: 0,
    luminance: 0.2644,
    contrastOnWhite: 3.34,
    contrastOnBlack: 6.29,
  ),

  /// LightSalmon3 (#af875f)
  lightSalmon3_137(
    code: 137,
    r: 175,
    g: 135,
    b: 95,
    luminance: 0.2727,
    contrastOnWhite: 3.25,
    contrastOnBlack: 6.45,
  ),

  /// RosyBrown (#af8787)
  rosyBrown_138(
    code: 138,
    r: 175,
    g: 135,
    b: 135,
    luminance: 0.2819,
    contrastOnWhite: 3.16,
    contrastOnBlack: 6.64,
  ),

  /// Grey63 (#af87af)
  grey63_139(
    code: 139,
    r: 175,
    g: 135,
    b: 175,
    luminance: 0.2954,
    contrastOnWhite: 3.04,
    contrastOnBlack: 6.91,
  ),

  /// MediumPurple2 (#af87d7)
  mediumPurple2_140(
    code: 140,
    r: 175,
    g: 135,
    b: 215,
    luminance: 0.3135,
    contrastOnWhite: 2.89,
    contrastOnBlack: 7.27,
  ),

  /// MediumPurple1 (#af87ff)
  mediumPurple1_141(
    code: 141,
    r: 175,
    g: 135,
    b: 255,
    luminance: 0.3366,
    contrastOnWhite: 2.72,
    contrastOnBlack: 7.73,
  ),

  /// Gold3 (#afaf00)
  gold3_142(
    code: 142,
    r: 175,
    g: 175,
    b: 0,
    luminance: 0.3977,
    contrastOnWhite: 2.35,
    contrastOnBlack: 8.95,
  ),

  /// DarkKhaki (#afaf5f)
  darkKhaki_143(
    code: 143,
    r: 175,
    g: 175,
    b: 95,
    luminance: 0.4060,
    contrastOnWhite: 2.30,
    contrastOnBlack: 9.12,
  ),

  /// NavajoWhite3 (#afaf87)
  navajoWhite3_144(
    code: 144,
    r: 175,
    g: 175,
    b: 135,
    luminance: 0.4152,
    contrastOnWhite: 2.26,
    contrastOnBlack: 9.30,
  ),

  /// Grey69 (#afafaf)
  grey69_145(
    code: 145,
    r: 175,
    g: 175,
    b: 175,
    luminance: 0.4287,
    contrastOnWhite: 2.19,
    contrastOnBlack: 9.57,
  ),

  /// LightSteelBlue3 (#afafd7)
  lightSteelBlue3_146(
    code: 146,
    r: 175,
    g: 175,
    b: 215,
    luminance: 0.4468,
    contrastOnWhite: 2.11,
    contrastOnBlack: 9.94,
  ),

  /// LightSteelBlue (#afafff)
  lightSteelBlue_147(
    code: 147,
    r: 175,
    g: 175,
    b: 255,
    luminance: 0.4699,
    contrastOnWhite: 2.02,
    contrastOnBlack: 10.40,
  ),

  /// Yellow3 (#afd700)
  yellow3_148(
    code: 148,
    r: 175,
    g: 215,
    b: 0,
    luminance: 0.5771,
    contrastOnWhite: 1.67,
    contrastOnBlack: 12.54,
  ),

  /// DarkOliveGreen3 (#afd75f)
  darkOliveGreen3_149(
    code: 149,
    r: 175,
    g: 215,
    b: 95,
    luminance: 0.5854,
    contrastOnWhite: 1.65,
    contrastOnBlack: 12.71,
  ),

  /// DarkSeaGreen3 (#afd787)
  darkSeaGreen3_150(
    code: 150,
    r: 175,
    g: 215,
    b: 135,
    luminance: 0.5946,
    contrastOnWhite: 1.63,
    contrastOnBlack: 12.89,
  ),

  /// DarkSeaGreen2 (#afd7af)
  darkSeaGreen2_151(
    code: 151,
    r: 175,
    g: 215,
    b: 175,
    luminance: 0.6081,
    contrastOnWhite: 1.60,
    contrastOnBlack: 13.16,
  ),

  /// LightCyan3 (#afd7d7)
  lightCyan3_152(
    code: 152,
    r: 175,
    g: 215,
    b: 215,
    luminance: 0.6262,
    contrastOnWhite: 1.55,
    contrastOnBlack: 13.52,
  ),

  /// LightSkyBlue1 (#afd7ff)
  lightSkyBlue1_153(
    code: 153,
    r: 175,
    g: 215,
    b: 255,
    luminance: 0.6493,
    contrastOnWhite: 1.50,
    contrastOnBlack: 13.99,
  ),

  /// GreenYellow (#afff00)
  greenYellow_154(
    code: 154,
    r: 175,
    g: 255,
    b: 0,
    luminance: 0.8063,
    contrastOnWhite: 1.23,
    contrastOnBlack: 17.13,
  ),

  /// DarkOliveGreen2 (#afff5f)
  darkOliveGreen2_155(
    code: 155,
    r: 175,
    g: 255,
    b: 95,
    luminance: 0.8146,
    contrastOnWhite: 1.21,
    contrastOnBlack: 17.29,
  ),

  /// PaleGreen1 (#afff87)
  paleGreen1_156(
    code: 156,
    r: 175,
    g: 255,
    b: 135,
    luminance: 0.8238,
    contrastOnWhite: 1.20,
    contrastOnBlack: 17.48,
  ),

  /// DarkSeaGreen2 (#afffaf)
  darkSeaGreen2_157(
    code: 157,
    r: 175,
    g: 255,
    b: 175,
    luminance: 0.8373,
    contrastOnWhite: 1.18,
    contrastOnBlack: 17.75,
  ),

  /// DarkSeaGreen1 (#afffd7)
  darkSeaGreen1_158(
    code: 158,
    r: 175,
    g: 255,
    b: 215,
    luminance: 0.8554,
    contrastOnWhite: 1.16,
    contrastOnBlack: 18.11,
  ),

  /// PaleTurquoise1 (#afffff)
  paleTurquoise1_159(
    code: 159,
    r: 175,
    g: 255,
    b: 255,
    luminance: 0.8785,
    contrastOnWhite: 1.13,
    contrastOnBlack: 18.57,
  ),

  /// Red3 (#d70000)
  red3_160(
    code: 160,
    r: 215,
    g: 0,
    b: 0,
    luminance: 0.1445,
    contrastOnWhite: 5.40,
    contrastOnBlack: 3.89,
  ),

  /// DeepPink3 (#d7005f)
  deepPink3_161(
    code: 161,
    r: 215,
    g: 0,
    b: 95,
    luminance: 0.1527,
    contrastOnWhite: 5.18,
    contrastOnBlack: 4.05,
  ),

  /// DeepPink3 (#d70087)
  deepPink3_162(
    code: 162,
    r: 215,
    g: 0,
    b: 135,
    luminance: 0.1620,
    contrastOnWhite: 4.95,
    contrastOnBlack: 4.24,
  ),

  /// Magenta3 (#d700af)
  magenta3_163(
    code: 163,
    r: 215,
    g: 0,
    b: 175,
    luminance: 0.1754,
    contrastOnWhite: 4.66,
    contrastOnBlack: 4.51,
  ),

  /// Magenta3 (#d700d7)
  magenta3_164(
    code: 164,
    r: 215,
    g: 0,
    b: 215,
    luminance: 0.1935,
    contrastOnWhite: 4.31,
    contrastOnBlack: 4.87,
  ),

  /// Magenta2 (#d700ff)
  magenta2_165(
    code: 165,
    r: 215,
    g: 0,
    b: 255,
    luminance: 0.2167,
    contrastOnWhite: 3.94,
    contrastOnBlack: 5.33,
  ),

  /// DarkOrange3 (#d75f00)
  darkOrange3_166(
    code: 166,
    r: 215,
    g: 95,
    b: 0,
    luminance: 0.2263,
    contrastOnWhite: 3.80,
    contrastOnBlack: 5.53,
  ),

  /// IndianRed (#d75f5f)
  indianRed_167(
    code: 167,
    r: 215,
    g: 95,
    b: 95,
    luminance: 0.2346,
    contrastOnWhite: 3.69,
    contrastOnBlack: 5.69,
  ),

  /// HotPink3 (#d75f87)
  hotPink3_168(
    code: 168,
    r: 215,
    g: 95,
    b: 135,
    luminance: 0.2438,
    contrastOnWhite: 3.57,
    contrastOnBlack: 5.88,
  ),

  /// HotPink2 (#d75faf)
  hotPink2_169(
    code: 169,
    r: 215,
    g: 95,
    b: 175,
    luminance: 0.2573,
    contrastOnWhite: 3.42,
    contrastOnBlack: 6.15,
  ),

  /// Orchid (#d75fd7)
  orchid_170(
    code: 170,
    r: 215,
    g: 95,
    b: 215,
    luminance: 0.2754,
    contrastOnWhite: 3.23,
    contrastOnBlack: 6.51,
  ),

  /// MediumOrchid1 (#d75fff)
  mediumOrchid1_171(
    code: 171,
    r: 215,
    g: 95,
    b: 255,
    luminance: 0.2985,
    contrastOnWhite: 3.01,
    contrastOnBlack: 6.97,
  ),

  /// Orange3 (#d78700)
  orange3_172(
    code: 172,
    r: 215,
    g: 135,
    b: 0,
    luminance: 0.3178,
    contrastOnWhite: 2.86,
    contrastOnBlack: 7.36,
  ),

  /// LightSalmon3 (#d7875f)
  lightSalmon3_173(
    code: 173,
    r: 215,
    g: 135,
    b: 95,
    luminance: 0.3260,
    contrastOnWhite: 2.79,
    contrastOnBlack: 7.52,
  ),

  /// LightPink3 (#d78787)
  lightPink3_174(
    code: 174,
    r: 215,
    g: 135,
    b: 135,
    luminance: 0.3352,
    contrastOnWhite: 2.73,
    contrastOnBlack: 7.70,
  ),

  /// Pink3 (#d787af)
  pink3_175(
    code: 175,
    r: 215,
    g: 135,
    b: 175,
    luminance: 0.3487,
    contrastOnWhite: 2.63,
    contrastOnBlack: 7.97,
  ),

  /// Plum3 (#d787d7)
  plum3_176(
    code: 176,
    r: 215,
    g: 135,
    b: 215,
    luminance: 0.3668,
    contrastOnWhite: 2.52,
    contrastOnBlack: 8.34,
  ),

  /// Violet (#d787ff)
  violet_177(
    code: 177,
    r: 215,
    g: 135,
    b: 255,
    luminance: 0.3900,
    contrastOnWhite: 2.39,
    contrastOnBlack: 8.80,
  ),

  /// Gold3 (#d7af00)
  gold3_178(
    code: 178,
    r: 215,
    g: 175,
    b: 0,
    luminance: 0.4511,
    contrastOnWhite: 2.10,
    contrastOnBlack: 10.02,
  ),

  /// LightGoldenrod3 (#d7af5f)
  lightGoldenrod3_179(
    code: 179,
    r: 215,
    g: 175,
    b: 95,
    luminance: 0.4593,
    contrastOnWhite: 2.06,
    contrastOnBlack: 10.19,
  ),

  /// Tan (#d7af87)
  tan_180(
    code: 180,
    r: 215,
    g: 175,
    b: 135,
    luminance: 0.4686,
    contrastOnWhite: 2.02,
    contrastOnBlack: 10.37,
  ),

  /// MistyRose3 (#d7afaf)
  mistyRose3_181(
    code: 181,
    r: 215,
    g: 175,
    b: 175,
    luminance: 0.4820,
    contrastOnWhite: 1.97,
    contrastOnBlack: 10.64,
  ),

  /// Thistle3 (#d7afd7)
  thistle3_182(
    code: 182,
    r: 215,
    g: 175,
    b: 215,
    luminance: 0.5001,
    contrastOnWhite: 1.91,
    contrastOnBlack: 11.00,
  ),

  /// Plum2 (#d7afff)
  plum2_183(
    code: 183,
    r: 215,
    g: 175,
    b: 255,
    luminance: 0.5233,
    contrastOnWhite: 1.83,
    contrastOnBlack: 11.47,
  ),

  /// Yellow3 (#d7d700)
  yellow3_184(
    code: 184,
    r: 215,
    g: 215,
    b: 0,
    luminance: 0.6305,
    contrastOnWhite: 1.54,
    contrastOnBlack: 13.61,
  ),

  /// Khaki3 (#d7d75f)
  khaki3_185(
    code: 185,
    r: 215,
    g: 215,
    b: 95,
    luminance: 0.6387,
    contrastOnWhite: 1.52,
    contrastOnBlack: 13.77,
  ),

  /// LightGoldenrod2 (#d7d787)
  lightGoldenrod2_186(
    code: 186,
    r: 215,
    g: 215,
    b: 135,
    luminance: 0.6480,
    contrastOnWhite: 1.50,
    contrastOnBlack: 13.96,
  ),

  /// LightYellow3 (#d7d7af)
  lightYellow3_187(
    code: 187,
    r: 215,
    g: 215,
    b: 175,
    luminance: 0.6614,
    contrastOnWhite: 1.48,
    contrastOnBlack: 14.23,
  ),

  /// Grey84 (#d7d7d7)
  grey84_188(
    code: 188,
    r: 215,
    g: 215,
    b: 215,
    luminance: 0.6795,
    contrastOnWhite: 1.44,
    contrastOnBlack: 14.59,
  ),

  /// LightSteelBlue1 (#d7d7ff)
  lightSteelBlue1_189(
    code: 189,
    r: 215,
    g: 215,
    b: 255,
    luminance: 0.7027,
    contrastOnWhite: 1.40,
    contrastOnBlack: 15.05,
  ),

  /// Yellow2 (#d7ff00)
  yellow2_190(
    code: 190,
    r: 215,
    g: 255,
    b: 0,
    luminance: 0.8597,
    contrastOnWhite: 1.15,
    contrastOnBlack: 18.19,
  ),

  /// DarkOliveGreen1 (#d7ff5f)
  darkOliveGreen1_191(
    code: 191,
    r: 215,
    g: 255,
    b: 95,
    luminance: 0.8679,
    contrastOnWhite: 1.14,
    contrastOnBlack: 18.36,
  ),

  /// DarkOliveGreen1 (#d7ff87)
  darkOliveGreen1_192(
    code: 192,
    r: 215,
    g: 255,
    b: 135,
    luminance: 0.8772,
    contrastOnWhite: 1.13,
    contrastOnBlack: 18.54,
  ),

  /// DarkSeaGreen1 (#d7ffaf)
  darkSeaGreen1_193(
    code: 193,
    r: 215,
    g: 255,
    b: 175,
    luminance: 0.8906,
    contrastOnWhite: 1.12,
    contrastOnBlack: 18.81,
  ),

  /// Honeydew2 (#d7ffd7)
  honeydew2_194(
    code: 194,
    r: 215,
    g: 255,
    b: 215,
    luminance: 0.9087,
    contrastOnWhite: 1.10,
    contrastOnBlack: 19.17,
  ),

  /// LightCyan1 (#d7ffff)
  lightCyan1_195(
    code: 195,
    r: 215,
    g: 255,
    b: 255,
    luminance: 0.9319,
    contrastOnWhite: 1.07,
    contrastOnBlack: 19.64,
  ),

  /// Red1 (#ff0000)
  red1_196(
    code: 196,
    r: 255,
    g: 0,
    b: 0,
    luminance: 0.2126,
    contrastOnWhite: 4.00,
    contrastOnBlack: 5.25,
  ),

  /// DeepPink2 (#ff005f)
  deepPink2_197(
    code: 197,
    r: 255,
    g: 0,
    b: 95,
    luminance: 0.2209,
    contrastOnWhite: 3.88,
    contrastOnBlack: 5.42,
  ),

  /// DeepPink1 (#ff0087)
  deepPink1_198(
    code: 198,
    r: 255,
    g: 0,
    b: 135,
    luminance: 0.2301,
    contrastOnWhite: 3.75,
    contrastOnBlack: 5.60,
  ),

  /// DeepPink1 (#ff00af)
  deepPink1_199(
    code: 199,
    r: 255,
    g: 0,
    b: 175,
    luminance: 0.2436,
    contrastOnWhite: 3.58,
    contrastOnBlack: 5.87,
  ),

  /// Magenta2 (#ff00d7)
  magenta2_200(
    code: 200,
    r: 255,
    g: 0,
    b: 215,
    luminance: 0.2617,
    contrastOnWhite: 3.37,
    contrastOnBlack: 6.23,
  ),

  /// Magenta1 (#ff00ff)
  magenta1_201(
    code: 201,
    r: 255,
    g: 0,
    b: 255,
    luminance: 0.2848,
    contrastOnWhite: 3.14,
    contrastOnBlack: 6.70,
  ),

  /// OrangeRed1 (#ff5f00)
  orangeRed1_202(
    code: 202,
    r: 255,
    g: 95,
    b: 0,
    luminance: 0.2944,
    contrastOnWhite: 3.05,
    contrastOnBlack: 6.89,
  ),

  /// IndianRed1 (#ff5f5f)
  indianRed1_203(
    code: 203,
    r: 255,
    g: 95,
    b: 95,
    luminance: 0.3027,
    contrastOnWhite: 2.98,
    contrastOnBlack: 7.05,
  ),

  /// IndianRed1 (#ff5f87)
  indianRed1_204(
    code: 204,
    r: 255,
    g: 95,
    b: 135,
    luminance: 0.3119,
    contrastOnWhite: 2.90,
    contrastOnBlack: 7.24,
  ),

  /// HotPink (#ff5faf)
  hotPink_205(
    code: 205,
    r: 255,
    g: 95,
    b: 175,
    luminance: 0.3254,
    contrastOnWhite: 2.80,
    contrastOnBlack: 7.51,
  ),

  /// HotPink (#ff5fd7)
  hotPink_206(
    code: 206,
    r: 255,
    g: 95,
    b: 215,
    luminance: 0.3435,
    contrastOnWhite: 2.67,
    contrastOnBlack: 7.87,
  ),

  /// MediumOrchid1 (#ff5fff)
  mediumOrchid1_207(
    code: 207,
    r: 255,
    g: 95,
    b: 255,
    luminance: 0.3666,
    contrastOnWhite: 2.52,
    contrastOnBlack: 8.33,
  ),

  /// DarkOrange (#ff8700)
  darkOrange_208(
    code: 208,
    r: 255,
    g: 135,
    b: 0,
    luminance: 0.3859,
    contrastOnWhite: 2.41,
    contrastOnBlack: 8.72,
  ),

  /// Salmon1 (#ff875f)
  salmon1_209(
    code: 209,
    r: 255,
    g: 135,
    b: 95,
    luminance: 0.3941,
    contrastOnWhite: 2.36,
    contrastOnBlack: 8.88,
  ),

  /// LightCoral (#ff8787)
  lightCoral_210(
    code: 210,
    r: 255,
    g: 135,
    b: 135,
    luminance: 0.4034,
    contrastOnWhite: 2.32,
    contrastOnBlack: 9.07,
  ),

  /// PaleVioletRed1 (#ff87af)
  paleVioletRed1_211(
    code: 211,
    r: 255,
    g: 135,
    b: 175,
    luminance: 0.4168,
    contrastOnWhite: 2.25,
    contrastOnBlack: 9.34,
  ),

  /// Orchid2 (#ff87d7)
  orchid2_212(
    code: 212,
    r: 255,
    g: 135,
    b: 215,
    luminance: 0.4349,
    contrastOnWhite: 2.17,
    contrastOnBlack: 9.70,
  ),

  /// Orchid1 (#ff87ff)
  orchid1_213(
    code: 213,
    r: 255,
    g: 135,
    b: 255,
    luminance: 0.4581,
    contrastOnWhite: 2.07,
    contrastOnBlack: 10.16,
  ),

  /// Orange1 (#ffaf00)
  orange1_214(
    code: 214,
    r: 255,
    g: 175,
    b: 0,
    luminance: 0.5192,
    contrastOnWhite: 1.84,
    contrastOnBlack: 11.38,
  ),

  /// SandyBrown (#ffaf5f)
  sandyBrown_215(
    code: 215,
    r: 255,
    g: 175,
    b: 95,
    luminance: 0.5275,
    contrastOnWhite: 1.82,
    contrastOnBlack: 11.55,
  ),

  /// LightSalmon1 (#ffaf87)
  lightSalmon1_216(
    code: 216,
    r: 255,
    g: 175,
    b: 135,
    luminance: 0.5367,
    contrastOnWhite: 1.79,
    contrastOnBlack: 11.73,
  ),

  /// LightPink1 (#ffafaf)
  lightPink1_217(
    code: 217,
    r: 255,
    g: 175,
    b: 175,
    luminance: 0.5502,
    contrastOnWhite: 1.75,
    contrastOnBlack: 12.00,
  ),

  /// Pink1 (#ffafd7)
  pink1_218(
    code: 218,
    r: 255,
    g: 175,
    b: 215,
    luminance: 0.5683,
    contrastOnWhite: 1.70,
    contrastOnBlack: 12.37,
  ),

  /// Plum1 (#ffafff)
  plum1_219(
    code: 219,
    r: 255,
    g: 175,
    b: 255,
    luminance: 0.5914,
    contrastOnWhite: 1.64,
    contrastOnBlack: 12.83,
  ),

  /// Gold1 (#ffd700)
  gold1_220(
    code: 220,
    r: 255,
    g: 215,
    b: 0,
    luminance: 0.6986,
    contrastOnWhite: 1.40,
    contrastOnBlack: 14.97,
  ),

  /// LightGoldenrod2 (#ffd75f)
  lightGoldenrod2_221(
    code: 221,
    r: 255,
    g: 215,
    b: 95,
    luminance: 0.7069,
    contrastOnWhite: 1.39,
    contrastOnBlack: 15.14,
  ),

  /// LightGoldenrod2 (#ffd787)
  lightGoldenrod2_222(
    code: 222,
    r: 255,
    g: 215,
    b: 135,
    luminance: 0.7161,
    contrastOnWhite: 1.37,
    contrastOnBlack: 15.32,
  ),

  /// NavajoWhite1 (#ffd7af)
  navajoWhite1_223(
    code: 223,
    r: 255,
    g: 215,
    b: 175,
    luminance: 0.7296,
    contrastOnWhite: 1.35,
    contrastOnBlack: 15.59,
  ),

  /// MistyRose1 (#ffd7d7)
  mistyRose1_224(
    code: 224,
    r: 255,
    g: 215,
    b: 215,
    luminance: 0.7477,
    contrastOnWhite: 1.32,
    contrastOnBlack: 15.95,
  ),

  /// Thistle1 (#ffd7ff)
  thistle1_225(
    code: 225,
    r: 255,
    g: 215,
    b: 255,
    luminance: 0.7708,
    contrastOnWhite: 1.28,
    contrastOnBlack: 16.42,
  ),

  /// Yellow1 (#ffff00)
  yellow1_226(
    code: 226,
    r: 255,
    g: 255,
    b: 0,
    luminance: 0.9278,
    contrastOnWhite: 1.07,
    contrastOnBlack: 19.56,
  ),

  /// LightGoldenrod1 (#ffff5f)
  lightGoldenrod1_227(
    code: 227,
    r: 255,
    g: 255,
    b: 95,
    luminance: 0.9361,
    contrastOnWhite: 1.06,
    contrastOnBlack: 19.72,
  ),

  /// Khaki1 (#ffff87)
  khaki1_228(
    code: 228,
    r: 255,
    g: 255,
    b: 135,
    luminance: 0.9453,
    contrastOnWhite: 1.05,
    contrastOnBlack: 19.91,
  ),

  /// Wheat1 (#ffffaf)
  wheat1_229(
    code: 229,
    r: 255,
    g: 255,
    b: 175,
    luminance: 0.9588,
    contrastOnWhite: 1.04,
    contrastOnBlack: 20.18,
  ),

  /// Cornsilk1 (#ffffd7)
  cornsilk1_230(
    code: 230,
    r: 255,
    g: 255,
    b: 215,
    luminance: 0.9769,
    contrastOnWhite: 1.02,
    contrastOnBlack: 20.54,
  ),

  /// Grey100 (#ffffff)
  grey100_231(
    code: 231,
    r: 255,
    g: 255,
    b: 255,
    luminance: 1.0000,
    contrastOnWhite: 1.00,
    contrastOnBlack: 21.00,
  ),

  /// Grey3 (#080808)
  grey3_232(
    code: 232,
    r: 8,
    g: 8,
    b: 8,
    luminance: 0.0024,
    contrastOnWhite: 20.03,
    contrastOnBlack: 1.05,
  ),

  /// Grey7 (#121212)
  grey7_233(
    code: 233,
    r: 18,
    g: 18,
    b: 18,
    luminance: 0.0060,
    contrastOnWhite: 18.73,
    contrastOnBlack: 1.12,
  ),

  /// Grey11 (#1c1c1c)
  grey11_234(
    code: 234,
    r: 28,
    g: 28,
    b: 28,
    luminance: 0.0116,
    contrastOnWhite: 17.04,
    contrastOnBlack: 1.23,
  ),

  /// Grey15 (#262626)
  grey15_235(
    code: 235,
    r: 38,
    g: 38,
    b: 38,
    luminance: 0.0194,
    contrastOnWhite: 15.13,
    contrastOnBlack: 1.39,
  ),

  /// Grey19 (#303030)
  grey19_236(
    code: 236,
    r: 48,
    g: 48,
    b: 48,
    luminance: 0.0296,
    contrastOnWhite: 13.20,
    contrastOnBlack: 1.59,
  ),

  /// Grey23 (#3a3a3a)
  grey23_237(
    code: 237,
    r: 58,
    g: 58,
    b: 58,
    luminance: 0.0423,
    contrastOnWhite: 11.37,
    contrastOnBlack: 1.85,
  ),

  /// Grey27 (#444444)
  grey27_238(
    code: 238,
    r: 68,
    g: 68,
    b: 68,
    luminance: 0.0578,
    contrastOnWhite: 9.74,
    contrastOnBlack: 2.16,
  ),

  /// Grey30 (#4e4e4e)
  grey30_239(
    code: 239,
    r: 78,
    g: 78,
    b: 78,
    luminance: 0.0762,
    contrastOnWhite: 8.32,
    contrastOnBlack: 2.52,
  ),

  /// Grey35 (#585858)
  grey35_240(
    code: 240,
    r: 88,
    g: 88,
    b: 88,
    luminance: 0.0976,
    contrastOnWhite: 7.11,
    contrastOnBlack: 2.95,
  ),

  /// Grey39 (#626262)
  grey39_241(
    code: 241,
    r: 98,
    g: 98,
    b: 98,
    luminance: 0.1221,
    contrastOnWhite: 6.10,
    contrastOnBlack: 3.44,
  ),

  /// Grey42 (#6c6c6c)
  grey42_242(
    code: 242,
    r: 108,
    g: 108,
    b: 108,
    luminance: 0.1500,
    contrastOnWhite: 5.25,
    contrastOnBlack: 4.00,
  ),

  /// Grey46 (#767676)
  grey46_243(
    code: 243,
    r: 118,
    g: 118,
    b: 118,
    luminance: 0.1812,
    contrastOnWhite: 4.54,
    contrastOnBlack: 4.62,
  ),

  /// Grey50 (#808080)
  grey50_244(
    code: 244,
    r: 128,
    g: 128,
    b: 128,
    luminance: 0.2159,
    contrastOnWhite: 3.95,
    contrastOnBlack: 5.32,
  ),

  /// Grey54 (#8a8a8a)
  grey54_245(
    code: 245,
    r: 138,
    g: 138,
    b: 138,
    luminance: 0.2542,
    contrastOnWhite: 3.45,
    contrastOnBlack: 6.08,
  ),

  /// Grey58 (#949494)
  grey58_246(
    code: 246,
    r: 148,
    g: 148,
    b: 148,
    luminance: 0.2961,
    contrastOnWhite: 3.03,
    contrastOnBlack: 6.92,
  ),

  /// Grey62 (#9e9e9e)
  grey62_247(
    code: 247,
    r: 158,
    g: 158,
    b: 158,
    luminance: 0.3419,
    contrastOnWhite: 2.68,
    contrastOnBlack: 7.84,
  ),

  /// Grey66 (#a8a8a8)
  grey66_248(
    code: 248,
    r: 168,
    g: 168,
    b: 168,
    luminance: 0.3916,
    contrastOnWhite: 2.38,
    contrastOnBlack: 8.83,
  ),

  /// Grey70 (#b2b2b2)
  grey70_249(
    code: 249,
    r: 178,
    g: 178,
    b: 178,
    luminance: 0.4452,
    contrastOnWhite: 2.12,
    contrastOnBlack: 9.90,
  ),

  /// Grey74 (#bcbcbc)
  grey74_250(
    code: 250,
    r: 188,
    g: 188,
    b: 188,
    luminance: 0.5029,
    contrastOnWhite: 1.90,
    contrastOnBlack: 11.06,
  ),

  /// Grey78 (#c6c6c6)
  grey78_251(
    code: 251,
    r: 198,
    g: 198,
    b: 198,
    luminance: 0.5647,
    contrastOnWhite: 1.71,
    contrastOnBlack: 12.29,
  ),

  /// Grey82 (#d0d0d0)
  grey82_252(
    code: 252,
    r: 208,
    g: 208,
    b: 208,
    luminance: 0.6308,
    contrastOnWhite: 1.54,
    contrastOnBlack: 13.62,
  ),

  /// Grey85 (#dadada)
  grey85_253(
    code: 253,
    r: 218,
    g: 218,
    b: 218,
    luminance: 0.7011,
    contrastOnWhite: 1.40,
    contrastOnBlack: 15.02,
  ),

  /// Grey89 (#e4e4e4)
  grey89_254(
    code: 254,
    r: 228,
    g: 228,
    b: 228,
    luminance: 0.7758,
    contrastOnWhite: 1.27,
    contrastOnBlack: 16.52,
  ),

  /// Grey93 (#eeeeee)
  grey93_255(
    code: 255,
    r: 238,
    g: 238,
    b: 238,
    luminance: 0.8550,
    contrastOnWhite: 1.16,
    contrastOnBlack: 18.10,
  ),
;

  final int code;
  final int r;
  final int g;
  final int b;
  final double luminance;
  final double contrastOnWhite;
  final double contrastOnBlack;

  const XtermColor({
    required this.code,
    required this.r,
    required this.g,
    required this.b,
    required this.luminance,
    required this.contrastOnWhite,
    required this.contrastOnBlack,
  });

  /// Calculate color distance using CIEDE2000.
  ///
  /// Returns perceptual color difference (ΔE).
  static double distance(XtermColor a, XtermColor b) {
    // Convert RGB to Lab
    final lab1 = _rgbToLab(a.r, a.g, a.b);
    final lab2 = _rgbToLab(b.r, b.g, b.b);
    return _ciede2000(lab1, lab2);
  }

  static (double L, double a, double b) _rgbToLab(int r, int g, int b) {
    // RGB to XYZ
    double pivotRgb(double n) {
      final v = n / 255.0;
      return v > 0.04045 ? math.pow((v + 0.055) / 1.055, 2.4).toDouble() : v / 12.92;
    }
    final rLinear = pivotRgb(r.toDouble()) * 100;
    final gLinear = pivotRgb(g.toDouble()) * 100;
    final bLinear = pivotRgb(b.toDouble()) * 100;

    // Observer = 2°, Illuminant = D65
    final x = rLinear * 0.4124564 + gLinear * 0.3575761 + bLinear * 0.1804375;
    final y = rLinear * 0.2126729 + gLinear * 0.7151522 + bLinear * 0.0721750;
    final z = rLinear * 0.0193339 + gLinear * 0.1191920 + bLinear * 0.9503041;

    // XYZ to Lab
    const refX = 95.047;
    const refY = 100.000;
    const refZ = 108.883;

    double pivotXyz(double n) {
      return n > 0.008856 ? math.pow(n, 1.0 / 3.0).toDouble() : (7.787 * n) + (16.0 / 116.0);
    }

    final xPivot = pivotXyz(x / refX);
    final yPivot = pivotXyz(y / refY);
    final zPivot = pivotXyz(z / refZ);

    final labL = (116.0 * yPivot) - 16.0;
    final labA = 500.0 * (xPivot - yPivot);
    final labB = 200.0 * (yPivot - zPivot);

    return (labL, labA, labB);
  }

  static double _ciede2000(
    (double, double, double) lab1,
    (double, double, double) lab2,
  ) {
    final l1 = lab1.$1;
    final a1 = lab1.$2;
    final b1 = lab1.$3;
    final l2 = lab2.$1;
    final a2 = lab2.$2;
    final b2 = lab2.$3;

    const kL = 1.0;
    const kC = 1.0;
    const kH = 1.0;
    const pi = 3.141592653589793;

    final c1 = math.sqrt(a1 * a1 + b1 * b1);
    final c2 = math.sqrt(a2 * a2 + b2 * b2);
    final cBar = (c1 + c2) / 2;

    final cBar7 = cBar * cBar * cBar * cBar * cBar * cBar * cBar;
    final g = 0.5 * (1 - math.sqrt(cBar7 / (cBar7 + 6103515625)));

    final a1Prime = a1 * (1 + g);
    final a2Prime = a2 * (1 + g);

    final c1Prime = math.sqrt(a1Prime * a1Prime + b1 * b1);
    final c2Prime = math.sqrt(a2Prime * a2Prime + b2 * b2);

    var h1Prime = math.atan2(b1, a1Prime) * 180 / pi;
    if (h1Prime < 0) h1Prime += 360;
    var h2Prime = math.atan2(b2, a2Prime) * 180 / pi;
    if (h2Prime < 0) h2Prime += 360;

    final deltaLPrime = l2 - l1;
    final deltaCPrime = c2Prime - c1Prime;

    double deltahPrime;
    if (c1Prime * c2Prime == 0) {
      deltahPrime = 0;
    } else {
      final diff = h2Prime - h1Prime;
      if (diff.abs() <= 180) {
        deltahPrime = diff;
      } else if (diff > 180) {
        deltahPrime = diff - 360;
      } else {
        deltahPrime = diff + 360;
      }
    }

    final deltaHPrime =
        2 * math.sqrt(c1Prime * c2Prime) * math.sin(deltahPrime * pi / 360);

    final lBarPrime = (l1 + l2) / 2;
    final cBarPrime = (c1Prime + c2Prime) / 2;

    double hBarPrime;
    if (c1Prime * c2Prime == 0) {
      hBarPrime = h1Prime + h2Prime;
    } else if ((h1Prime - h2Prime).abs() <= 180) {
      hBarPrime = (h1Prime + h2Prime) / 2;
    } else if (h1Prime + h2Prime < 360) {
      hBarPrime = (h1Prime + h2Prime + 360) / 2;
    } else {
      hBarPrime = (h1Prime + h2Prime - 360) / 2;
    }

    final t = 1 -
        0.17 * math.cos((hBarPrime - 30) * pi / 180) +
        0.24 * math.cos(2 * hBarPrime * pi / 180) +
        0.32 * math.cos((3 * hBarPrime + 6) * pi / 180) -
        0.20 * math.cos((4 * hBarPrime - 63) * pi / 180);

    final deltaTheta =
        30 * math.exp(-((hBarPrime - 275) / 25) * ((hBarPrime - 275) / 25));

    final cBarPrime7 =
        cBarPrime * cBarPrime * cBarPrime * cBarPrime * cBarPrime * cBarPrime * cBarPrime;
    final rc = 2 * math.sqrt(cBarPrime7 / (cBarPrime7 + 6103515625));

    final lBarPrimeMinus50Sq = (lBarPrime - 50) * (lBarPrime - 50);
    final sl =
        1 + (0.015 * lBarPrimeMinus50Sq) / math.sqrt(20 + lBarPrimeMinus50Sq);
    final sc = 1 + 0.045 * cBarPrime;
    final sh = 1 + 0.015 * cBarPrime * t;
    final rt = -math.sin(2 * deltaTheta * pi / 180) * rc;

    final dL = deltaLPrime / (kL * sl);
    final dC = deltaCPrime / (kC * sc);
    final dH = deltaHPrime / (kH * sh);

    return math.sqrt(dL * dL + dC * dC + dH * dH + rt * dC * dH);
  }
}
