// GENERATED FILE - DO NOT EDIT
// Generated by tool/generate_xterm_colors.dart

import 'package:chirp/src/ansi/console_color.dart';

/// The 256-color xterm palette as [IndexedColor] constants.
///
/// Codes 0-15 are standard ANSI colors (prefer [Ansi16] for these).
/// Codes 16-231 are a 6x6x6 color cube.
/// Codes 232-255 are a grayscale ramp.
///
/// ## Example
///
/// ```dart
/// buffer.pushStyle(foreground: Ansi256.orange1_214);
/// buffer.write("Warning!");
/// buffer.popStyle();
/// ```
abstract final class Ansi256 {
  /// Black (#000000)
  static const black_0 = IndexedColor(0);

  /// Maroon (#800000)
  static const red_1 = IndexedColor(1);

  /// Green (#008000)
  static const green_2 = IndexedColor(2);

  /// Olive (#808000)
  static const yellow_3 = IndexedColor(3);

  /// Navy (#000080)
  static const blue_4 = IndexedColor(4);

  /// Purple (#800080)
  static const magenta_5 = IndexedColor(5);

  /// Teal (#008080)
  static const cyan_6 = IndexedColor(6);

  /// Silver (#c0c0c0)
  static const white_7 = IndexedColor(7);

  /// Grey (#808080)
  static const brightBlack_8 = IndexedColor(8);

  /// Red (#ff0000)
  static const brightRed_9 = IndexedColor(9);

  /// Lime (#00ff00)
  static const brightGreen_10 = IndexedColor(10);

  /// Yellow (#ffff00)
  static const brightYellow_11 = IndexedColor(11);

  /// Blue (#0000ff)
  static const brightBlue_12 = IndexedColor(12);

  /// Fuchsia (#ff00ff)
  static const brightMagenta_13 = IndexedColor(13);

  /// Aqua (#00ffff)
  static const brightCyan_14 = IndexedColor(14);

  /// White (#ffffff)
  static const brightWhite_15 = IndexedColor(15);

  /// Grey0 (#000000)
  static const grey0_16 = IndexedColor(16);

  /// NavyBlue (#00005f)
  static const navyBlue_17 = IndexedColor(17);

  /// DarkBlue (#000087)
  static const darkBlue_18 = IndexedColor(18);

  /// Blue3 (#0000af)
  static const blue3_19 = IndexedColor(19);

  /// Blue3 (#0000d7)
  static const blue3_20 = IndexedColor(20);

  /// Blue1 (#0000ff)
  static const blue1_21 = IndexedColor(21);

  /// DarkGreen (#005f00)
  static const darkGreen_22 = IndexedColor(22);

  /// DeepSkyBlue4 (#005f5f)
  static const deepSkyBlue4_23 = IndexedColor(23);

  /// DeepSkyBlue4 (#005f87)
  static const deepSkyBlue4_24 = IndexedColor(24);

  /// DeepSkyBlue4 (#005faf)
  static const deepSkyBlue4_25 = IndexedColor(25);

  /// DodgerBlue3 (#005fd7)
  static const dodgerBlue3_26 = IndexedColor(26);

  /// DodgerBlue2 (#005fff)
  static const dodgerBlue2_27 = IndexedColor(27);

  /// Green4 (#008700)
  static const green4_28 = IndexedColor(28);

  /// SpringGreen4 (#00875f)
  static const springGreen4_29 = IndexedColor(29);

  /// Turquoise4 (#008787)
  static const turquoise4_30 = IndexedColor(30);

  /// DeepSkyBlue3 (#0087af)
  static const deepSkyBlue3_31 = IndexedColor(31);

  /// DeepSkyBlue3 (#0087d7)
  static const deepSkyBlue3_32 = IndexedColor(32);

  /// DodgerBlue1 (#0087ff)
  static const dodgerBlue1_33 = IndexedColor(33);

  /// Green3 (#00af00)
  static const green3_34 = IndexedColor(34);

  /// SpringGreen3 (#00af5f)
  static const springGreen3_35 = IndexedColor(35);

  /// DarkCyan (#00af87)
  static const darkCyan_36 = IndexedColor(36);

  /// LightSeaGreen (#00afaf)
  static const lightSeaGreen_37 = IndexedColor(37);

  /// DeepSkyBlue2 (#00afd7)
  static const deepSkyBlue2_38 = IndexedColor(38);

  /// DeepSkyBlue1 (#00afff)
  static const deepSkyBlue1_39 = IndexedColor(39);

  /// Green3 (#00d700)
  static const green3_40 = IndexedColor(40);

  /// SpringGreen3 (#00d75f)
  static const springGreen3_41 = IndexedColor(41);

  /// SpringGreen2 (#00d787)
  static const springGreen2_42 = IndexedColor(42);

  /// Cyan3 (#00d7af)
  static const cyan3_43 = IndexedColor(43);

  /// DarkTurquoise (#00d7d7)
  static const darkTurquoise_44 = IndexedColor(44);

  /// Turquoise2 (#00d7ff)
  static const turquoise2_45 = IndexedColor(45);

  /// Green1 (#00ff00)
  static const green1_46 = IndexedColor(46);

  /// SpringGreen2 (#00ff5f)
  static const springGreen2_47 = IndexedColor(47);

  /// SpringGreen1 (#00ff87)
  static const springGreen1_48 = IndexedColor(48);

  /// MediumSpringGreen (#00ffaf)
  static const mediumSpringGreen_49 = IndexedColor(49);

  /// Cyan2 (#00ffd7)
  static const cyan2_50 = IndexedColor(50);

  /// Cyan1 (#00ffff)
  static const cyan1_51 = IndexedColor(51);

  /// DarkRed (#5f0000)
  static const darkRed_52 = IndexedColor(52);

  /// DeepPink4 (#5f005f)
  static const deepPink4_53 = IndexedColor(53);

  /// Purple4 (#5f0087)
  static const purple4_54 = IndexedColor(54);

  /// Purple4 (#5f00af)
  static const purple4_55 = IndexedColor(55);

  /// Purple3 (#5f00d7)
  static const purple3_56 = IndexedColor(56);

  /// BlueViolet (#5f00ff)
  static const blueViolet_57 = IndexedColor(57);

  /// Orange4 (#5f5f00)
  static const orange4_58 = IndexedColor(58);

  /// Grey37 (#5f5f5f)
  static const grey37_59 = IndexedColor(59);

  /// MediumPurple4 (#5f5f87)
  static const mediumPurple4_60 = IndexedColor(60);

  /// SlateBlue3 (#5f5faf)
  static const slateBlue3_61 = IndexedColor(61);

  /// SlateBlue3 (#5f5fd7)
  static const slateBlue3_62 = IndexedColor(62);

  /// RoyalBlue1 (#5f5fff)
  static const royalBlue1_63 = IndexedColor(63);

  /// Chartreuse4 (#5f8700)
  static const chartreuse4_64 = IndexedColor(64);

  /// DarkSeaGreen4 (#5f875f)
  static const darkSeaGreen4_65 = IndexedColor(65);

  /// PaleTurquoise4 (#5f8787)
  static const paleTurquoise4_66 = IndexedColor(66);

  /// SteelBlue (#5f87af)
  static const steelBlue_67 = IndexedColor(67);

  /// SteelBlue3 (#5f87d7)
  static const steelBlue3_68 = IndexedColor(68);

  /// CornflowerBlue (#5f87ff)
  static const cornflowerBlue_69 = IndexedColor(69);

  /// Chartreuse3 (#5faf00)
  static const chartreuse3_70 = IndexedColor(70);

  /// DarkSeaGreen4 (#5faf5f)
  static const darkSeaGreen4_71 = IndexedColor(71);

  /// CadetBlue (#5faf87)
  static const cadetBlue_72 = IndexedColor(72);

  /// CadetBlue (#5fafaf)
  static const cadetBlue_73 = IndexedColor(73);

  /// SkyBlue3 (#5fafd7)
  static const skyBlue3_74 = IndexedColor(74);

  /// SteelBlue1 (#5fafff)
  static const steelBlue1_75 = IndexedColor(75);

  /// Chartreuse3 (#5fd700)
  static const chartreuse3_76 = IndexedColor(76);

  /// PaleGreen3 (#5fd75f)
  static const paleGreen3_77 = IndexedColor(77);

  /// SeaGreen3 (#5fd787)
  static const seaGreen3_78 = IndexedColor(78);

  /// Aquamarine3 (#5fd7af)
  static const aquamarine3_79 = IndexedColor(79);

  /// MediumTurquoise (#5fd7d7)
  static const mediumTurquoise_80 = IndexedColor(80);

  /// SteelBlue1 (#5fd7ff)
  static const steelBlue1_81 = IndexedColor(81);

  /// Chartreuse2 (#5fff00)
  static const chartreuse2_82 = IndexedColor(82);

  /// SeaGreen2 (#5fff5f)
  static const seaGreen2_83 = IndexedColor(83);

  /// SeaGreen1 (#5fff87)
  static const seaGreen1_84 = IndexedColor(84);

  /// SeaGreen1 (#5fffaf)
  static const seaGreen1_85 = IndexedColor(85);

  /// Aquamarine1 (#5fffd7)
  static const aquamarine1_86 = IndexedColor(86);

  /// DarkSlateGray2 (#5fffff)
  static const darkSlateGray2_87 = IndexedColor(87);

  /// DarkRed (#870000)
  static const darkRed_88 = IndexedColor(88);

  /// DeepPink4 (#87005f)
  static const deepPink4_89 = IndexedColor(89);

  /// DarkMagenta (#870087)
  static const darkMagenta_90 = IndexedColor(90);

  /// DarkMagenta (#8700af)
  static const darkMagenta_91 = IndexedColor(91);

  /// DarkViolet (#8700d7)
  static const darkViolet_92 = IndexedColor(92);

  /// Purple (#8700ff)
  static const purple_93 = IndexedColor(93);

  /// Orange4 (#875f00)
  static const orange4_94 = IndexedColor(94);

  /// LightPink4 (#875f5f)
  static const lightPink4_95 = IndexedColor(95);

  /// Plum4 (#875f87)
  static const plum4_96 = IndexedColor(96);

  /// MediumPurple3 (#875faf)
  static const mediumPurple3_97 = IndexedColor(97);

  /// MediumPurple3 (#875fd7)
  static const mediumPurple3_98 = IndexedColor(98);

  /// SlateBlue1 (#875fff)
  static const slateBlue1_99 = IndexedColor(99);

  /// Yellow4 (#878700)
  static const yellow4_100 = IndexedColor(100);

  /// Wheat4 (#87875f)
  static const wheat4_101 = IndexedColor(101);

  /// Grey53 (#878787)
  static const grey53_102 = IndexedColor(102);

  /// LightSlateGrey (#8787af)
  static const lightSlateGrey_103 = IndexedColor(103);

  /// MediumPurple (#8787d7)
  static const mediumPurple_104 = IndexedColor(104);

  /// LightSlateBlue (#8787ff)
  static const lightSlateBlue_105 = IndexedColor(105);

  /// Yellow4 (#87af00)
  static const yellow4_106 = IndexedColor(106);

  /// DarkOliveGreen3 (#87af5f)
  static const darkOliveGreen3_107 = IndexedColor(107);

  /// DarkSeaGreen (#87af87)
  static const darkSeaGreen_108 = IndexedColor(108);

  /// LightSkyBlue3 (#87afaf)
  static const lightSkyBlue3_109 = IndexedColor(109);

  /// LightSkyBlue3 (#87afd7)
  static const lightSkyBlue3_110 = IndexedColor(110);

  /// SkyBlue2 (#87afff)
  static const skyBlue2_111 = IndexedColor(111);

  /// Chartreuse2 (#87d700)
  static const chartreuse2_112 = IndexedColor(112);

  /// DarkOliveGreen3 (#87d75f)
  static const darkOliveGreen3_113 = IndexedColor(113);

  /// PaleGreen3 (#87d787)
  static const paleGreen3_114 = IndexedColor(114);

  /// DarkSeaGreen3 (#87d7af)
  static const darkSeaGreen3_115 = IndexedColor(115);

  /// DarkSlateGray3 (#87d7d7)
  static const darkSlateGray3_116 = IndexedColor(116);

  /// SkyBlue1 (#87d7ff)
  static const skyBlue1_117 = IndexedColor(117);

  /// Chartreuse1 (#87ff00)
  static const chartreuse1_118 = IndexedColor(118);

  /// LightGreen (#87ff5f)
  static const lightGreen_119 = IndexedColor(119);

  /// LightGreen (#87ff87)
  static const lightGreen_120 = IndexedColor(120);

  /// PaleGreen1 (#87ffaf)
  static const paleGreen1_121 = IndexedColor(121);

  /// Aquamarine1 (#87ffd7)
  static const aquamarine1_122 = IndexedColor(122);

  /// DarkSlateGray1 (#87ffff)
  static const darkSlateGray1_123 = IndexedColor(123);

  /// Red3 (#af0000)
  static const red3_124 = IndexedColor(124);

  /// DeepPink4 (#af005f)
  static const deepPink4_125 = IndexedColor(125);

  /// MediumVioletRed (#af0087)
  static const mediumVioletRed_126 = IndexedColor(126);

  /// Magenta3 (#af00af)
  static const magenta3_127 = IndexedColor(127);

  /// DarkViolet (#af00d7)
  static const darkViolet_128 = IndexedColor(128);

  /// Purple (#af00ff)
  static const purple_129 = IndexedColor(129);

  /// DarkOrange3 (#af5f00)
  static const darkOrange3_130 = IndexedColor(130);

  /// IndianRed (#af5f5f)
  static const indianRed_131 = IndexedColor(131);

  /// HotPink3 (#af5f87)
  static const hotPink3_132 = IndexedColor(132);

  /// MediumOrchid3 (#af5faf)
  static const mediumOrchid3_133 = IndexedColor(133);

  /// MediumOrchid (#af5fd7)
  static const mediumOrchid_134 = IndexedColor(134);

  /// MediumPurple2 (#af5fff)
  static const mediumPurple2_135 = IndexedColor(135);

  /// DarkGoldenrod (#af8700)
  static const darkGoldenrod_136 = IndexedColor(136);

  /// LightSalmon3 (#af875f)
  static const lightSalmon3_137 = IndexedColor(137);

  /// RosyBrown (#af8787)
  static const rosyBrown_138 = IndexedColor(138);

  /// Grey63 (#af87af)
  static const grey63_139 = IndexedColor(139);

  /// MediumPurple2 (#af87d7)
  static const mediumPurple2_140 = IndexedColor(140);

  /// MediumPurple1 (#af87ff)
  static const mediumPurple1_141 = IndexedColor(141);

  /// Gold3 (#afaf00)
  static const gold3_142 = IndexedColor(142);

  /// DarkKhaki (#afaf5f)
  static const darkKhaki_143 = IndexedColor(143);

  /// NavajoWhite3 (#afaf87)
  static const navajoWhite3_144 = IndexedColor(144);

  /// Grey69 (#afafaf)
  static const grey69_145 = IndexedColor(145);

  /// LightSteelBlue3 (#afafd7)
  static const lightSteelBlue3_146 = IndexedColor(146);

  /// LightSteelBlue (#afafff)
  static const lightSteelBlue_147 = IndexedColor(147);

  /// Yellow3 (#afd700)
  static const yellow3_148 = IndexedColor(148);

  /// DarkOliveGreen3 (#afd75f)
  static const darkOliveGreen3_149 = IndexedColor(149);

  /// DarkSeaGreen3 (#afd787)
  static const darkSeaGreen3_150 = IndexedColor(150);

  /// DarkSeaGreen2 (#afd7af)
  static const darkSeaGreen2_151 = IndexedColor(151);

  /// LightCyan3 (#afd7d7)
  static const lightCyan3_152 = IndexedColor(152);

  /// LightSkyBlue1 (#afd7ff)
  static const lightSkyBlue1_153 = IndexedColor(153);

  /// GreenYellow (#afff00)
  static const greenYellow_154 = IndexedColor(154);

  /// DarkOliveGreen2 (#afff5f)
  static const darkOliveGreen2_155 = IndexedColor(155);

  /// PaleGreen1 (#afff87)
  static const paleGreen1_156 = IndexedColor(156);

  /// DarkSeaGreen2 (#afffaf)
  static const darkSeaGreen2_157 = IndexedColor(157);

  /// DarkSeaGreen1 (#afffd7)
  static const darkSeaGreen1_158 = IndexedColor(158);

  /// PaleTurquoise1 (#afffff)
  static const paleTurquoise1_159 = IndexedColor(159);

  /// Red3 (#d70000)
  static const red3_160 = IndexedColor(160);

  /// DeepPink3 (#d7005f)
  static const deepPink3_161 = IndexedColor(161);

  /// DeepPink3 (#d70087)
  static const deepPink3_162 = IndexedColor(162);

  /// Magenta3 (#d700af)
  static const magenta3_163 = IndexedColor(163);

  /// Magenta3 (#d700d7)
  static const magenta3_164 = IndexedColor(164);

  /// Magenta2 (#d700ff)
  static const magenta2_165 = IndexedColor(165);

  /// DarkOrange3 (#d75f00)
  static const darkOrange3_166 = IndexedColor(166);

  /// IndianRed (#d75f5f)
  static const indianRed_167 = IndexedColor(167);

  /// HotPink3 (#d75f87)
  static const hotPink3_168 = IndexedColor(168);

  /// HotPink2 (#d75faf)
  static const hotPink2_169 = IndexedColor(169);

  /// Orchid (#d75fd7)
  static const orchid_170 = IndexedColor(170);

  /// MediumOrchid1 (#d75fff)
  static const mediumOrchid1_171 = IndexedColor(171);

  /// Orange3 (#d78700)
  static const orange3_172 = IndexedColor(172);

  /// LightSalmon3 (#d7875f)
  static const lightSalmon3_173 = IndexedColor(173);

  /// LightPink3 (#d78787)
  static const lightPink3_174 = IndexedColor(174);

  /// Pink3 (#d787af)
  static const pink3_175 = IndexedColor(175);

  /// Plum3 (#d787d7)
  static const plum3_176 = IndexedColor(176);

  /// Violet (#d787ff)
  static const violet_177 = IndexedColor(177);

  /// Gold3 (#d7af00)
  static const gold3_178 = IndexedColor(178);

  /// LightGoldenrod3 (#d7af5f)
  static const lightGoldenrod3_179 = IndexedColor(179);

  /// Tan (#d7af87)
  static const tan_180 = IndexedColor(180);

  /// MistyRose3 (#d7afaf)
  static const mistyRose3_181 = IndexedColor(181);

  /// Thistle3 (#d7afd7)
  static const thistle3_182 = IndexedColor(182);

  /// Plum2 (#d7afff)
  static const plum2_183 = IndexedColor(183);

  /// Yellow3 (#d7d700)
  static const yellow3_184 = IndexedColor(184);

  /// Khaki3 (#d7d75f)
  static const khaki3_185 = IndexedColor(185);

  /// LightGoldenrod2 (#d7d787)
  static const lightGoldenrod2_186 = IndexedColor(186);

  /// LightYellow3 (#d7d7af)
  static const lightYellow3_187 = IndexedColor(187);

  /// Grey84 (#d7d7d7)
  static const grey84_188 = IndexedColor(188);

  /// LightSteelBlue1 (#d7d7ff)
  static const lightSteelBlue1_189 = IndexedColor(189);

  /// Yellow2 (#d7ff00)
  static const yellow2_190 = IndexedColor(190);

  /// DarkOliveGreen1 (#d7ff5f)
  static const darkOliveGreen1_191 = IndexedColor(191);

  /// DarkOliveGreen1 (#d7ff87)
  static const darkOliveGreen1_192 = IndexedColor(192);

  /// DarkSeaGreen1 (#d7ffaf)
  static const darkSeaGreen1_193 = IndexedColor(193);

  /// Honeydew2 (#d7ffd7)
  static const honeydew2_194 = IndexedColor(194);

  /// LightCyan1 (#d7ffff)
  static const lightCyan1_195 = IndexedColor(195);

  /// Red1 (#ff0000)
  static const red1_196 = IndexedColor(196);

  /// DeepPink2 (#ff005f)
  static const deepPink2_197 = IndexedColor(197);

  /// DeepPink1 (#ff0087)
  static const deepPink1_198 = IndexedColor(198);

  /// DeepPink1 (#ff00af)
  static const deepPink1_199 = IndexedColor(199);

  /// Magenta2 (#ff00d7)
  static const magenta2_200 = IndexedColor(200);

  /// Magenta1 (#ff00ff)
  static const magenta1_201 = IndexedColor(201);

  /// OrangeRed1 (#ff5f00)
  static const orangeRed1_202 = IndexedColor(202);

  /// IndianRed1 (#ff5f5f)
  static const indianRed1_203 = IndexedColor(203);

  /// IndianRed1 (#ff5f87)
  static const indianRed1_204 = IndexedColor(204);

  /// HotPink (#ff5faf)
  static const hotPink_205 = IndexedColor(205);

  /// HotPink (#ff5fd7)
  static const hotPink_206 = IndexedColor(206);

  /// MediumOrchid1 (#ff5fff)
  static const mediumOrchid1_207 = IndexedColor(207);

  /// DarkOrange (#ff8700)
  static const darkOrange_208 = IndexedColor(208);

  /// Salmon1 (#ff875f)
  static const salmon1_209 = IndexedColor(209);

  /// LightCoral (#ff8787)
  static const lightCoral_210 = IndexedColor(210);

  /// PaleVioletRed1 (#ff87af)
  static const paleVioletRed1_211 = IndexedColor(211);

  /// Orchid2 (#ff87d7)
  static const orchid2_212 = IndexedColor(212);

  /// Orchid1 (#ff87ff)
  static const orchid1_213 = IndexedColor(213);

  /// Orange1 (#ffaf00)
  static const orange1_214 = IndexedColor(214);

  /// SandyBrown (#ffaf5f)
  static const sandyBrown_215 = IndexedColor(215);

  /// LightSalmon1 (#ffaf87)
  static const lightSalmon1_216 = IndexedColor(216);

  /// LightPink1 (#ffafaf)
  static const lightPink1_217 = IndexedColor(217);

  /// Pink1 (#ffafd7)
  static const pink1_218 = IndexedColor(218);

  /// Plum1 (#ffafff)
  static const plum1_219 = IndexedColor(219);

  /// Gold1 (#ffd700)
  static const gold1_220 = IndexedColor(220);

  /// LightGoldenrod2 (#ffd75f)
  static const lightGoldenrod2_221 = IndexedColor(221);

  /// LightGoldenrod2 (#ffd787)
  static const lightGoldenrod2_222 = IndexedColor(222);

  /// NavajoWhite1 (#ffd7af)
  static const navajoWhite1_223 = IndexedColor(223);

  /// MistyRose1 (#ffd7d7)
  static const mistyRose1_224 = IndexedColor(224);

  /// Thistle1 (#ffd7ff)
  static const thistle1_225 = IndexedColor(225);

  /// Yellow1 (#ffff00)
  static const yellow1_226 = IndexedColor(226);

  /// LightGoldenrod1 (#ffff5f)
  static const lightGoldenrod1_227 = IndexedColor(227);

  /// Khaki1 (#ffff87)
  static const khaki1_228 = IndexedColor(228);

  /// Wheat1 (#ffffaf)
  static const wheat1_229 = IndexedColor(229);

  /// Cornsilk1 (#ffffd7)
  static const cornsilk1_230 = IndexedColor(230);

  /// Grey100 (#ffffff)
  static const grey100_231 = IndexedColor(231);

  /// Grey3 (#080808)
  static const grey3_232 = IndexedColor(232);

  /// Grey7 (#121212)
  static const grey7_233 = IndexedColor(233);

  /// Grey11 (#1c1c1c)
  static const grey11_234 = IndexedColor(234);

  /// Grey15 (#262626)
  static const grey15_235 = IndexedColor(235);

  /// Grey19 (#303030)
  static const grey19_236 = IndexedColor(236);

  /// Grey23 (#3a3a3a)
  static const grey23_237 = IndexedColor(237);

  /// Grey27 (#444444)
  static const grey27_238 = IndexedColor(238);

  /// Grey30 (#4e4e4e)
  static const grey30_239 = IndexedColor(239);

  /// Grey35 (#585858)
  static const grey35_240 = IndexedColor(240);

  /// Grey39 (#626262)
  static const grey39_241 = IndexedColor(241);

  /// Grey42 (#6c6c6c)
  static const grey42_242 = IndexedColor(242);

  /// Grey46 (#767676)
  static const grey46_243 = IndexedColor(243);

  /// Grey50 (#808080)
  static const grey50_244 = IndexedColor(244);

  /// Grey54 (#8a8a8a)
  static const grey54_245 = IndexedColor(245);

  /// Grey58 (#949494)
  static const grey58_246 = IndexedColor(246);

  /// Grey62 (#9e9e9e)
  static const grey62_247 = IndexedColor(247);

  /// Grey66 (#a8a8a8)
  static const grey66_248 = IndexedColor(248);

  /// Grey70 (#b2b2b2)
  static const grey70_249 = IndexedColor(249);

  /// Grey74 (#bcbcbc)
  static const grey74_250 = IndexedColor(250);

  /// Grey78 (#c6c6c6)
  static const grey78_251 = IndexedColor(251);

  /// Grey82 (#d0d0d0)
  static const grey82_252 = IndexedColor(252);

  /// Grey85 (#dadada)
  static const grey85_253 = IndexedColor(253);

  /// Grey89 (#e4e4e4)
  static const grey89_254 = IndexedColor(254);

  /// Grey93 (#eeeeee)
  static const grey93_255 = IndexedColor(255);
}
