// GENERATED FILE - DO NOT EDIT
// Generated by tool/generate_readable_colors.dart
//
// These colors are readable on both light and dark terminal backgrounds
// and do not interfere with red (errors) or yellow (warnings).
//
// Filtering criteria:
// - Distance to red (Ansi256.red_1) > 30
// - Distance to yellow (Ansi256.yellow_3) > 30
// - Contrast on white >= 2.12
// - Contrast on black >= 3.1
// - Saturation >= 16% (excludes grays)

import 'package:chirp/src/ansi/ansi256.g.dart';
import 'package:chirp/src/ansi/console_color.dart';

/// Low saturation colors (17-33%) - subtle, muted tones.
const List<IndexedColor> readableColorsLowSaturation = [
  Ansi256.hotPink3_132,
  Ansi256.plum4_96,
  Ansi256.mediumOrchid3_133,
  Ansi256.grey63_139,
  Ansi256.mediumPurple3_97,
  Ansi256.mediumPurple4_60,
  Ansi256.slateBlue3_61,
  Ansi256.lightSlateGrey_103,
  Ansi256.steelBlue_67,
  Ansi256.cadetBlue_73,
  Ansi256.lightSkyBlue3_109,
  Ansi256.rosyBrown_138,
];

/// Medium saturation colors (34-60%) - balanced, clear tones.
const List<IndexedColor> readableColorsMediumSaturation = [
  Ansi256.hotPink3_168,
  Ansi256.pink3_175,
  Ansi256.hotPink2_169,
  Ansi256.orchid_170,
  Ansi256.plum3_176,
  Ansi256.mediumOrchid_134,
  Ansi256.mediumPurple2_140,
  Ansi256.mediumPurple3_98,
  Ansi256.slateBlue3_62,
  Ansi256.mediumPurple_104,
  Ansi256.steelBlue3_68,
  Ansi256.lightSkyBlue3_110,
  Ansi256.skyBlue3_74,
  Ansi256.lightSalmon3_173,
  Ansi256.lightPink3_174,
];

/// High saturation colors (61-100%) - vibrant, vivid tones.
const List<IndexedColor> readableColorsHighSaturation = [
  Ansi256.indianRed1_204,
  Ansi256.paleVioletRed1_211,
  Ansi256.hotPink_205,
  Ansi256.deepPink1_198,
  Ansi256.deepPink3_162,
  Ansi256.orchid2_212,
  Ansi256.deepPink1_199,
  Ansi256.hotPink_206,
  Ansi256.mediumVioletRed_126,
  Ansi256.magenta3_163,
  Ansi256.magenta2_200,
  Ansi256.magenta3_127,
  Ansi256.brightMagenta_13,
  Ansi256.mediumOrchid1_207,
  Ansi256.magenta1_201,
  Ansi256.magenta3_164,
  Ansi256.magenta2_165,
  Ansi256.darkViolet_128,
  Ansi256.mediumOrchid1_171,
  Ansi256.purple_129,
  Ansi256.violet_177,
  Ansi256.purple_93,
  Ansi256.mediumPurple2_135,
  Ansi256.mediumPurple1_141,
  Ansi256.slateBlue1_99,
  Ansi256.lightSlateBlue_105,
  Ansi256.royalBlue1_63,
  Ansi256.cornflowerBlue_69,
  Ansi256.skyBlue2_111,
  Ansi256.dodgerBlue2_27,
  Ansi256.dodgerBlue3_26,
  Ansi256.steelBlue1_75,
  Ansi256.dodgerBlue1_33,
  Ansi256.deepSkyBlue4_25,
  Ansi256.deepSkyBlue3_32,
  Ansi256.deepSkyBlue1_39,
  Ansi256.deepSkyBlue3_31,
  Ansi256.deepSkyBlue2_38,
  Ansi256.cyan_6,
  Ansi256.lightSeaGreen_37,
  Ansi256.turquoise4_30,
  Ansi256.darkOrange_208,
  Ansi256.orangeRed1_202,
  Ansi256.salmon1_209,
  Ansi256.indianRed1_203,
  Ansi256.lightCoral_210,
];

/// All readable colors combined (low + medium + high saturation).
const List<IndexedColor> readableColors = [
  ...readableColorsLowSaturation,
  ...readableColorsMediumSaturation,
  ...readableColorsHighSaturation,
];
